### ISSUE TITLE
[Issue]: Certain Satellaview games not working

### ISSUE THREAD

**Issue by SylvieWrath** [dborth/snes9xgx#1007]
### Describe the bug

I have some ROMs that play fine on my PC but don't play correctly via snes9xGX. For the most part, the ones that work on PC also work on the Wii, but there's a few games i can't get running in SNES9xGX. It's a short list:
-BS Fire Emblem parts 1 through 4 (including the English translations, which i have working on PC as well) (CRC32: 13561465, CRC32: 11715A99, CRC32: 643AADB4, CRC32: 78DE9569 for parts 1,2,3,4 TRANSLATED, respectively)
-Konae-chan no Dokidoki Penguin Kazoku (CRC32: 218B11F8)

### To Reproduce

Run any of the described ROMs on SNES9XGX

### Expected behavior

Black screen. Emulator still works and you can access the emulator menu, but nothing happens in the game.

**Comment by niuus** [comment]
> ### Describe the bug
> I have some ROMs that play fine on my PC but don't play correctly via snes9xGX. For the most part, the ones that work on PC also work on the Wii, but there's a few games i can't get running in SNES9xGX. It's a short list: -BS Fire Emblem parts 1 through 4 (including the English translations, which i have working on PC as well) (CRC32: 13561465, CRC32: 11715A99, CRC32: 643AADB4, CRC32: 78DE9569 for parts 1,2,3,4 TRANSLATED, respectively) -Konae-chan no Dokidoki Penguin Kazoku (CRC32: 218B11F8)

You need to run those games through the BIOS or they just won't work.

**Comment by saulfabregwiivc** [comment]
> > ### Describe the bug
> > I have some ROMs that play fine on my PC but don't play correctly via snes9xGX. For the most part, the ones that work on PC also work on the Wii, but there's a few games i can't get running in SNES9xGX. It's a short list: -BS Fire Emblem parts 1 through 4 (including the English translations, which i have working on PC as well) (CRC32: 13561465, CRC32: 11715A99, CRC32: 643AADB4, CRC32: 78DE9569 for parts 1,2,3,4 TRANSLATED, respectively) -Konae-chan no Dokidoki Penguin Kazoku (CRC32: 218B11F8)
> 
> You need to run those games through the BIOS or they just won't work.

Yep.
These games work fine for me but these need the BS-X BIOS.

**Comment by SylvieWrath** [comment]
Wait, how do you run them through the BIOS via SNES9xGX? I have the BIOS file, i just couldn't find documentation about where to actually put it or what to name it to make Satellaview work properly. If i set that up, will it force all my other Satellaview games to play through the BIOS too?

**Comment by niuus** [comment]
> Wait, how do you run them through the BIOS via SNES9xGX? I have the BIOS file, i just couldn't find documentation about where to actually put it or what to name it to make Satellaview work properly. If i set that up, will it force all my other Satellaview games to play through the BIOS too?

root:/snes9xgx/BS-X.BIN

Try it and you will see.
