### ISSUE TITLE
[Issue]: Tried compiling. What does this mean and how can I fix it??

### ISSUE THREAD

**Issue by PiRhoManiacal** [dborth/snes9xgx#1016]
### Describe the bug

![image](https://user-images.githubusercontent.com/94188079/173168168-1cea0c5c-4268-4ef6-89e9-350e93f2b725.png)
hoping this is "clear and concise" enough
I'm just looking for answers

### To Reproduce

I dunno

### Expected behavior

I expected it to compile smoothly???

**Comment by dborth** [comment]
Not sure what you're doing to compile, but if you download devkitppc and the latest libogc this compiles fine

**Comment by saulfabregwiivc** [comment]
Use latest devkitPPC. libOGC, and portlibs and it will compile just fine
