### ISSUE TITLE
[Wii] [Question]: Compiled version of Snes9x GX with UStealth support?

### ISSUE THREAD

**Issue by saulfabregwiivc** [dborth/snes9xgx#1017]
### Describe your question

So, i've seen this old issue https://github.com/dborth/snes9xgx/issues/700

I was thinking in if you could compile a Snes9x GX version with UStealth support by using my mod of the latest libFAT SVN for make it compatible with UStealth (for Wii U), which i've posted it here: https://github.com/saulfabregwiivc/libfat/releases/tag/v1.1.5-SVN-27062020-UStealth

UStealth is a program on Windows and Wii Homebrew. Usually, if the Wii U senses a NTFS or Fat32 partition it will ask if you want to format it at every boot. UStealth "hides" the drive from being detected so you don't get that nagging message. There are other uses for it too, but the point is that UStealth hides the hard drive from being seen. So multiple different apps add support for UStealth so that it can see a hard drive, even if it is hidden. More can be read about it at the link below, including some threads talking about it, and an example of it being added to Not64 and Genesis Plus GX.

https://gbatemp.net/threads/ustealth-wii-u-format-disk-nag-workaround.352786/
https://github.com/rudism/ustealth.sh/blob/master/README.md

Could you check this and try to make an official Snes9x GX build with UStealth?
(Also can do the same for FCE Ultra GX and Visual Boy Advance GX?)

Greetings :)

**Comment by dborth** [comment]
I'd rather see this get merged into libfat and then I'm happy to put out a new version. I don't really want to be customizing the libs this project is built on.
