### ISSUE TITLE
[Issue]: Jerky scrolling in FF titles

### ISSUE THREAD

**Issue by minsec7829** [dborth/snes9xgx#1020]
### Describe the bug

The screen does not scroll smoothly in certain areas of FF2us, FF5, and FF3us. This can be seen in the opening cutscene of FF3us and the Narshe area, the area where Lenna is first met in FF5, and the exterior of Baron Castle in FF2us. These are some of the first areas in their respective games.

This does not happen with Snes9x on my Android phone. I've only seen this on the Gamecube; I wanted to test the Wii version of the emulator to see how it did, but I don't think I'll have the chance anytime soon.

### To Reproduce

Get to the areas listed and get the screen to scroll.

### Expected behavior

Smooth scrolling.

**Comment by dborth** [comment]
Sorry, not going to look into this myself.

**Comment by Papy-G** [comment]
Is the output set to the appropriate Rom's framerate?
Did you try to disable frameskipping?
