### ISSUE TITLE
[Issue]: Audio noise in FF2us

### ISSUE THREAD

**Issue by minsec7829** [dborth/snes9xgx#1021]
### Describe the bug

In the Baron Castle area at the beginning of FF2us, there's some odd scratchy noise / audio garbage faintly playing along with the normal BGM. I don't know if this happens in any other areas of the game.

This is in the Gamecube version of the emulator.

### To Reproduce

Get to Baron Castle and listen to the music.

### Expected behavior

Clean audio.

**Comment by dborth** [comment]
Sounds like an emulation issue. No idea where to start with this one. If it happens on the desktop version of snes9x you should report it there.
