### ISSUE TITLE
[Issue]: mouse movement stucks with gamecube controller

### ISSUE THREAD

**Issue by DigiDwrf** [dborth/snes9xgx#1022]
### Describe the bug

cursor is not able to pass from certain limit

### To Reproduce

tried on Mario Paint. Mouse cursor won't be able to reach zones near to the border of the screen

### Expected behavior

cursor showld be able to run all over the screen, tha same way wiimote does (and original SNES mouse)

**Comment by dborth** [comment]
Yeah unfortunately this is as good as I can make it.
