### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by philivy** [dborth/snes9xgx#1023]
### Describe your question

hello , 
I have a gcloader new generation without soldering. 
I boot  swiss 0.6
I run snes9xhx 
snes dol try to access dvd but cant 
it try to access my gecko sd card , but can't read 
I install rom smc to rom directories but nothing , still same problem 

may you help me ? 

thankx

**Comment by philivy** [comment]
the new gcloader is connected via dvd socket , so there is no original dvd 
a sd card with swiss , boot the system ,  it just use for that emulate a boot dvd swiss.

**Comment by dborth** [comment]
Sorry, I can't help. You can try asking on gc-forever.com or gbatemp.net
