### ISSUE TITLE
[Issue]: Nintendo Campus Challenge ‘92 not working

### ISSUE THREAD

**Issue by plemak88** [dborth/snes9xgx#1044]
### Describe the bug

As the ROM for this game is actually in 3 ROMs, the game doesn’t work.

### To Reproduce

Simply try to load the game.

### Expected behavior

It should load, and play for 6:21.

**Comment by dborth** [comment]
Really the support is determined by the support that snes9x (https://github.com/snes9xgit/snes9x) has. If there's problems there, I'd report it to them.
