### ISSUE TITLE
[Issue]: Gamecube builds not working

### ISSUE THREAD

**Issue by niuus** [dborth/snes9xgx#1051]
### Describe the bug

Gamecube builds stopped working after 4.5.3. They load to a black screen.

Using:
[Pre-release](https://github.com/dborth/snes9xgx/releases/tag/Pre-release) and a new compile from the downloaded source.

Tested with SD Gecko+SD Media Launcher disc, or booting the snes9xgx dol through Swiss (1400-1420). Also changed SD cards with a freshly formatted one, same result.

### To Reproduce

Open the DOL.

### Expected behavior

Should work, as 4.5.3 version.

**Comment by dborth** [comment]
Unfortunately I don't have a way to test on GameCube so I don't have a way to track down which commit broke this.

**Comment by bladeoner** [comment]
@niuus this week some changes where added, can you try with the latest Pre-release?

**Comment by niuus** [comment]
> 

Hi @bladeoner. Sure, i'll check these builds in some minutes. I'll reply again with the results.

**Comment by niuus** [comment]
Results are in:

> Test 1
Working

> Test 2
Working

> Test 3
Working

> Pre-release (Optimize code (#1060))
Still not working

**Comment by bladeoner** [comment]
@niuus ok, that's a good start, to narrow down the scope, can you test the next three builds?

Test 1 commit: https://github.com/dborth/snes9xgx/commit/c74bfa27a034f72f872b08b65b85bc1b92828b05
Download: https://github.com/dborth/snes9xgx/suites/10671939935/artifacts/533720654

Test 2 commit: https://github.com/dborth/snes9xgx/commit/890383fa9665ce0cd8eda52adb7d7d34a558660f
Download: https://github.com/dborth/snes9xgx/suites/10563630309/artifacts/525665328

Test 3 commit: https://github.com/dborth/snes9xgx/commit/c84d99060ce574c9bacf25f38bf5bb0fa2e7b298
Download: https://github.com/dborth/snes9xgx/suites/10563099731/artifacts/525625876

**Comment by niuus** [comment]
> @niuus ok, that's a good start, to narrow down the scope, can you test the next three builds?
> 
> Test 1 commit: [c74bfa2](https://github.com/dborth/snes9xgx/commit/c74bfa27a034f72f872b08b65b85bc1b92828b05) Download: https://github.com/dborth/snes9xgx/suites/10671939935/artifacts/533720654
> 
> Test 2 commit: [890383f](https://github.com/dborth/snes9xgx/commit/890383fa9665ce0cd8eda52adb7d7d34a558660f) Download: https://github.com/dborth/snes9xgx/suites/10563630309/artifacts/525665328
> 
> Test 3 commit: [c84d990](https://github.com/dborth/snes9xgx/commit/c84d99060ce574c9bacf25f38bf5bb0fa2e7b298) Download: https://github.com/dborth/snes9xgx/suites/10563099731/artifacts/525625876

Hi @bladeoner. I think i've found the problem, it was #1045. Might be doing something not permitted on the Cube at startup related to the unsupported PAL addition.

If you can do a build with your devkit of #1045 and #1043, I can confirm you.

**Comment by niuus** [comment]
> @niuus ok, that's a good start, to narrow down the scope, can you test the next three builds?
> 
> Test 1 commit: [c74bfa2](https://github.com/dborth/snes9xgx/commit/c74bfa27a034f72f872b08b65b85bc1b92828b05) Download: https://github.com/dborth/snes9xgx/suites/10671939935/artifacts/533720654
> 
> Test 2 commit: [890383f](https://github.com/dborth/snes9xgx/commit/890383fa9665ce0cd8eda52adb7d7d34a558660f) Download: https://github.com/dborth/snes9xgx/suites/10563630309/artifacts/525665328
> 
> Test 3 commit: [c84d990](https://github.com/dborth/snes9xgx/commit/c84d99060ce574c9bacf25f38bf5bb0fa2e7b298) Download: https://github.com/dborth/snes9xgx/suites/10563099731/artifacts/525625876

Hi @bladeoner. None worked, I think the problem is definitely #1045. Might be doing something not permitted on the Cube at startup related to the unsupported PAL addition.

If you can do a build with your devkit for #1043, I can confirm you.

**Comment by bladeoner** [comment]
Hi @niuus, here you go:

Commit 1043: https://github.com/dborth/snes9xgx/commit/d193277ecaabe8b7cfbd69dcb2138f3080846b48
File: [Snes9xGX-GameCube#1043.zip](https://github.com/dborth/snes9xgx/files/11010556/Snes9xGX-GameCube.1043.zip)

**Comment by niuus** [comment]
> Hi @niuus, here you go:
> 
> Commit 1043: [d193277](https://github.com/dborth/snes9xgx/commit/d193277ecaabe8b7cfbd69dcb2138f3080846b48) File: [Snes9xGX-GameCube#1043.zip](https://github.com/dborth/snes9xgx/files/11010556/Snes9xGX-GameCube.1043.zip)

Back to this, sorry for the absence. Okey, so this one finally works. Tanooki made a fix, that you can check here:
https://gbatemp.net/threads/snes9x-rx-a-new-fork.527131/post-10103981

**Comment by niuus** [comment]
> Hi @niuus, here you go:
> 
> Commit 1043: [d193277](https://github.com/dborth/snes9xgx/commit/d193277ecaabe8b7cfbd69dcb2138f3080846b48) File: [Snes9xGX-GameCube#1043.zip](https://github.com/dborth/snes9xgx/files/11010556/Snes9xGX-GameCube.1043.zip)

Back to this, sorry for the absence. Okey, so this one finally works. Tanooki16 noticed his mistake and made a fix, that you can check here:
https://gbatemp.net/threads/snes9x-rx-a-new-fork.527131/post-10103981

I briefly tested and it works correctly.

**Comment by bladeoner** [comment]
@niuus can you test the attached file, I opened a PR with the fix:
[Snes9xGX-GameCube_Video_Fix.zip](https://github.com/dborth/snes9xgx/files/11071218/Snes9xGX-GameCube_Video_Fix.zip)

**Comment by Papy-G** [comment]
Happy to see that this build is properly working with both SDGecko and SD2SP2 at last (used to be stuck to 4.4.9 because of that).
