### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by cuttsjrightware** [dborth/snes9xgx#1063]
### Describe the bug

The gamecube version of snes9xgx won't load the in game menu using L+R+X+Y.

### To Reproduce

The controller input of L+R+X+Y on the new(ish) Old Skool hori gamepad doesn't work.

I also tried on a regular gamecube controller and that didn't work.

What did work was the left C-Stick on the gamecube controller. 

### Expected behavior

Menu to load in game.

**Comment by dborth** [comment]
I don't see that as a home mapping? I do see x+y+start

**Comment by cuttsjrightware** [comment]
Thank you for the feedback.

I jsut found out that my L button on my Old Skool controller was broken.
Doing L+R+Start on a regular GameCube controller did work.

This is no longer a bug.

Thank you for making this too btw :).
