### ISSUE TITLE
[Question]: 480i with Gamecube Component cables on Trinitron CRT

### ISSUE THREAD

**Issue by stefcep** [dborth/snes9xgx#1065]
### Describe your question

My TV ( Sony Trinitron PAL) cannot display 480p.  The UI opens in 480p.  The screen is doubled and unreadable.  I don't want to boot in composite and then plug in my (expensive) component cables in and out all the time.  Can I select the UI to display in 480i?

**Comment by InfiniteBlueGX** [comment]
You should be able to set this by going into the video settings, then changing:
Video Mode -> PAL (60hz)
Rendering -> Original (240p)  [not required but highly recommended if using a CRT]

**Comment by dborth** [comment]
That's correct, if your preferences aren't saved or are set to "auto" video mode then you will end up in progressive mode on gamecube due to this code:

#ifdef HW_DOL
			/* we have component cables, but the preferred mode is interlaced
			 * why don't we switch into progressive?
			 * on the Wii, the user can do this themselves on their Wii Settings */
			if(VIDEO_HaveComponentCable())
				mode = &TVNtsc480Prog;
			#endif

but if you've saved your preferences to the above, you'll bypass this check.
Closing this there's a workaround.
