### ISSUE TITLE
[Question]:  It is there a way to configure generic usb controller in snes9xGX

### ISSUE THREAD

**Issue by marcosadsjunior** [dborth/snes9xgx#1068]
### Describe your question

Guys, I've a USB snes like controler that I use in my PC. Now I'm using the wii with a CRT TV to play my most retro games but I couldn't configure this USB controller in the snes9xgx. I'm curent using the newest version although differrent of Nitendont that regonize the controller conected on USB port, snes9xgx doesn't or at least I wouldn't able to find it.

Is there a way to configure this generics controller or is just that ones showed in configuration?

Thanks a lot

**Comment by dborth** [comment]
No, no one has built that feature into this.
