### ISSUE TITLE
[Question]: Is netplay possible with SNES emulation on the Wii?

### ISSUE THREAD

**Issue by BevP90** [dborth/snes9xgx#1078]
### Describe your question

Is P2P netplay possible with SNES emulation on the Wii? This would be an amazing feature to have, just some delay based netcode that would allow 2 player games to be played over the internet with a player on either side. I think the Wii is more than powerful enough to do this, but curious to know what you think.

**Comment by dborth** [comment]
Sure why not? Someone needs to actually code it though.

**Comment by BevP90** [comment]
> Sure why not? Someone needs to actually code it though.

I'll have to ask around and see if anyone can do it. Would get a donation going
