### ISSUE TITLE
[Issue]: Wii Channel version not working

### ISSUE THREAD

**Issue by GalaxiumNation** [dborth/snes9xgx#1081]
### Describe the bug

I saw another bug report with this exact same issue.
The channel opens, Shows a loading screen for about 1/2 a second and goes straight back to the wii menu

I dont have the boot.dol for the application for homebrew, so that could be the problem? (If you have it please could u gimme it?)

### To Reproduce

Open channel.

### Expected behavior

Launches snes9xgx

### Relevant log output

```shell
Idk
```

### Screenshots

I'll upload a video once my phone charges

**Comment by dborth** [comment]
Download the emulator not just the channel and go read the readme.
