### ISSUE TITLE
[Issue]: snes9xgx 4.5.4 unable to scan SD2SP2

### ISSUE THREAD

**Issue by boktai1000** [dborth/snes9xgx#1085]
### Describe the bug

Device not found, even though snes9xgx is being booted from and running off of my SD2SP2 Pro.

### To Reproduce

SD2SP2 Pro installed in GameCube
Booting Swiss via Action Replay -> SD Gecko
Launch snes9xgx, which is stored on my 400GB microSD card connected to my SD2SP2 Pro
snes9xgx is unable to see an SD card connected

### Expected behavior

snes9xgx would be able to see, identify, and browse my SD2SP2

### Screenshots

Unable to grab screenshots off of hardware at this time.

**Comment by dborth** [comment]
Is your sd card formatted with fat32 or exfat?

**Comment by boktai1000** [comment]
> Is your sd card formatted with fat32 or exfat?

exFAT

SanDisk Ultra 400GB MicroSDXC UHSI Memory Card
Model: SDSQUAR-400G-GN6MA
SKU: 6092830

![image](https://github.com/dborth/snes9xgx/assets/9054563/0b3a46bc-0ce8-4197-88a1-cc218abca9e4)

**Comment by dborth** [comment]
Perfect, then that's the reason. Swiss supports exfat but this emulator doesn't. Format it to fat32 and it'll work.

**Comment by boktai1000** [comment]
Is that possible for this size of a card? I formatted with the recommended / official Panasonic SD Card Format utility.

Additionally, would it make sense to open a request for exFAT support - is that within the realm of possibility? Just curious - thanks!

**Comment by dborth** [comment]
Yes it's absolutely possible to format it to fat32, use a fat32 format tool. Yes it's possible to add exfat but I'm not going to do it so there's no point to opening the request. If someone submits a pull request, I'll merge it.
