### ISSUE TITLE
USB HID support for USB mice and USB gamepads/gamepad adapters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dborth/snes9xgx#357]
```
Describe the enhancement desired or suggested change:

Now that libOGC has added USB HID support, can we get this added to
snes9x-gx?  There are a few uses for this:

1. people who have USB adapters for using their retro controllers on the PC
(like myself :) would be able to use those adapters for the Wii.
2. games which require the mouse (i.e. Mario Paint) would be able to use a
real mouse.

Thanks!
```

Original issue reported on code.google.com by `thaman...@gmail.com` on 15 Nov 2009 at 11:26

**Comment by rchuncleskeleton** [comment]
So then this will never be implemented? Is it hard to do or just not something you're willing to do? Would be awesome to be able to connect my use mouse to the Wii for playing mouse based games like Mario Paint. I do hope you'll  consider it.

**Comment by askotx** [comment]
@rchuncleskeleton you are welcome to make a pull request, like Tantric said: this is not a request forum. So you're free to do it and make a pull request.
