### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by NintendoWiiGuy** [dborth/snes9xgx#675]
i cannot get it to show in my homebrew channel help!

**Comment by EarlSleek** [comment]
well for one you have to copy the hbc folder, but there is a major issue on this there is no boot.dol therefore it is null snes will not work

**Comment by EarlSleek** [comment]
https://github.com/dborth/snes9x-gx/releases/download/4.3.2/Snes9x.GX.Cheat.Files.zip   this will work, it is an older version of it, but if you want to play snes this is the way, especially since most of these have been shut down

**Comment by EarlSleek** [comment]
sorry sorry wrong link, its this one   https://github.com/dborth/snes9x-gx/releases   just find Snes9x.GX.4.3.1.zip this link works

**Comment by askotx** [comment]
Try new version 4.3.6 and if it works now close this issue please

**Comment by dborth** [comment]
Sorry, this isn't a support forum. Try some other place like gbatemp.net for help.
