### ISSUE TITLE
wrong selection color for Main Menu dialog buttons

### ISSUE THREAD

**Issue by joshg253** [dborth/snes9xgx#677]
EDIT: Using this on an actual Wii console.

Selecting the Main Menu button shows a "Quit this game? [...]" message with OK highlighted yellow but it actually cancels instead of quitting.

The default of having Cancel selected is good, but the display does not reflect that -- Cancel must be yellow to actually quit the game return to the Main Main menu.

**Comment by joshg253** [comment]
Behavior is the same for the Reset dialog.

Cancel is actually selected but "highlighted" in black, the using the d-pad left & right reflects moving the black "highlight".

**Comment by joshg253** [comment]
Now I see closed issues reporting the same problem. I also found when it was changed (5169aa4d909e64ab8356fe81081e956e7881d4ce) and I can understand why the change was made:
    Highlighted/selected buttons throughout the rest of the app are yellow-bordered, but those Prompt Windows also happen to be yellow. So you either get dark-highlighted buttons on yellow dialog (the above change), or yellow-highlighted buttons on yellow Prompt Windows (default), which is not quite as noticeable due to lack of contrast, but at least it's consistent.

I've rolled back the aforementioned changes in my fork and will look into changing the color of the Prompt Windows so the buttons can remain consistent and also visible.

**Comment by askotx** [comment]
Fixed thanks to Zopenko
