### ISSUE TITLE
SNES9x 1.43 core version

### ISSUE THREAD

**Issue by filevans** [dborth/snes9xgx#679]
please could you do an alternative SNES9x 1.43 or 1.51 core version option updated to the lastest bugfixes, as these cores run faster than 1.53. and the slight lack of accuracy is not noticable

the reason is there are a few games that slow down and sound stutters on 1.53, as 1.53 needs a lot more cpu power

for example try this game: Jikkyou Oshaberi Parodius, there is slow down on the title screen, but it does not slow down on version 1.51 or 1.43!

either an alternative boot.dol with 1.51 on it with all the new updates, or one that contains both cores selectable please

thank you for listening

**Comment by askotx** [comment]
No, we re using 1.53 version, coding a new version requires a lot of work.
You could try new version 4.3.6 version and check again if works better.
