### ISSUE TITLE
USB issues. 

### ISSUE THREAD

**Issue by Orvis25** [dborth/snes9xgx#680]
Hey, so I recently installed Snes9x GX 4.3.2 and have discovered a massive issue that is preventing me from playing games. 

When I launch a game and start playing, everything is fine. But after like 10 min of playing if i hit the home button to bring up the menu so i can save, my HDD turns off, and the wii no longer recognizes it until I hard reset both the wii, and unplug my hdd. 

I think this is an programming issue with something that Snes9x GX. FCEUltraGX, WiiSX and VBA GX use because I have the same problem in all three. 

Now i know it is not an HDD issue because I have USB Leader GX installed, and I can play games for hours, close and change games after a few hours without any issues. 

Anyone know if this will be patched, or know of a fix?

**Comment by askotx** [comment]
Use recent version -4.3.6- and test again please, if it's fixed, close issue please.

**Comment by Orvis25** [comment]
just updated and tested. 

Still having issues were when going back the the menu, saving or loading after extended periods of not using it, my external will shut itself off, and i have to hard reboot.

**Comment by bladeoner** [comment]
Hi, @Orvis25 I don't think it will make any difference, but you can try to use this new unofficial build 4.3.8.
It also includes BPS soft patching and MSU1 support thanks to Qwertymodo:
[SNES9X.GX.4.3.8.zip](https://github.com/dborth/snes9xgx/files/1601145/SNES9X.GX.4.3.8.zip)

**Comment by dborth** [comment]
Sounds like the hard drive might be going to sleep and not waking up. The USB support isn't going to be improved unless someone submits a patch. I'd suggest running off an SD card if you continue to have issues.
