### ISSUE TITLE
SF Classic controller support

### ISSUE THREAD

**Issue by cshea85** [dborth/snes9xgx#682]
When using SF classic controller, everything works except d-pad. I have looked everyhwhere, only to find dead links to recompiled files claiming a fix. Is there an updated file i need to download to fix this issue?
Wii Version 4.3u
SNES9xGX 4.3.2

**Comment by rmarinvsn** [comment]
Hello, 

Same problem here. Mine is a TTX Tech Snes controller for wii. I'd like to try to fix this myself. I have programming skills, but before I start digging in the code, do you have any hint? Where should I start looking? Is something doable by changing your code or is it a deeper level problem?

**Comment by rmarinvsn** [comment]
Hi,
There is a new version of libogc 1.8.15 which claims to solve the problems with 3rd party controllers. I've try to compile snes9xgx with the new version but I failed. I've compiled the wii samples of devkitpro, so I know that my installation is fine and I've also installed the portlibs, but when I try to compile I get this kind of errors:

c:/snes9xgx-master/source/preferences.cpp: In function 'int preparePrefsData()':
c:/snes9xgx-master/source/preferences.cpp:164:50: error: invalid conversion from 'u32* {aka long unsigned int*}' to 'unsigned int*' [-fpermissive]
  createXMLController(btnmap[CTRL_PAD][CTRLR_GCPAD], "btnmap_pad_gcpad", "SNES Pad - GameCube Controller");

Any help would be highly appreciated.

Best,
Raúl

**Comment by rmarinvsn** [comment]
Hi,

Just to let you know, this project doesn't compile with devkitppc r28. I've installed r24, which is the version mentioned in the wiki (although it says "or higher")  and now I'm able to compile the project. 

I've recompiled it using libgc 1.8.15 and I will try this .dol to see if my controller works.

I will let you know if my controller works as soon as I have time to test it.

**Comment by askotx** [comment]
I compile dol file with devkitpro r26, and libogc 1.8.12.
Just remember this is an issue tracker not a forum
