### ISSUE TITLE
Loading saves restarts game

### ISSUE THREAD

**Issue by Glomgold** [dborth/snes9xgx#683]
Firstly, thank you for the work with the program.

I've also tried older versions, several of them but the same thing happens. The save is created and is in the folder I have checked on the computer, but when I load the save the game just restarts and starts from the beginning.

I don't get any error messages, I've turned off all the auto options. I've tried saving on both SD and USB.

Thank you for help.

**Comment by askotx** [comment]
Works fine here, which version are you using?

**Comment by dborth** [comment]
Closing for lack of response.
