### ISSUE TITLE
WBFS drives crash the emulator. How would I fix this?

### ISSUE THREAD

**Issue by Nawor3565** [dborth/snes9xgx#685]
When a WBFS USB drive is inserted when the emulator starts, it just takes me to a blank menu, and I have to force shut off the Wii. When there is no drive inserted, it works fine. Im guessing its because its searching for roms on the drive, even though its set to "SD" and not "Auto Detect" in the settings. How would I fix this?

**Comment by GB-CG** [comment]
Have you tried using a USB drive formated to FAT32 for that emulator?

**Comment by askotx** [comment]
sne9xgx just work with FAT32 format for SD and USB drives.
