### ISSUE TITLE
Adding Snes9x Next enhancements from retroarch to Snes9x gx

### ISSUE THREAD

**Issue by gadesx** [dborth/snes9xgx#691]
Some games like Chrono Trigger runs perfectly without sound crackling or frame rate
issues with the snes9x next of retroarch (playing without filters, directly in CRT at 240p in two cases)

**Comment by roflcopter777** [comment]
Have you tested out 4.3.6 and 4.3.7? Most, if not all audio issues should be nonissue as the emulator has been revamped this year.

**Comment by askotx** [comment]
You could make a pull request, if you code it, this is not an issue
