### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by troglo-mcdino** [dborth/snes9xgx#694]
I've noticed that Snes9xgx only runs games in 320x224. The native resolution of the SNES is 256x224, so the games appear stretched in the emulator. I know the original SNES stretched games too but I would like to play SNES games in a "pixel perfect" mode so to speak.

**Comment by dborth** [comment]
The emulator is already using the native modes supported on the Wii, see https://libogc.devkitpro.org/group__gxrmode__obj.html

There's also already options to prevent the stretch. So there's really nothing to be done here.
