### ISSUE TITLE
Covers/Screenshots not working

### ISSUE THREAD

**Issue by ghost-wolves** [dborth/snes9xgx#695]
I have the correct folders created (snes9xgx/screenshots & covers) and the files named correctly but nothing shows up. I even take new screenshots, switch the display over to screenshots in the menu and they still don't show up. The screenshot appears in the correct folder on the SD card after I take it, it just won't show up in the GUI.

**Comment by Batchicken** [comment]
Are they .PNG files? The documentation says that any pictures have to be .PNG files. (Although I can't guarantee it'll work since mine just crashes every time I try to select a game with cover art on it)

**Comment by dborth** [comment]
Seems to work fine for me with the latest codebase. Perhaps there's some compatibility issue with the files you're trying to use. I'd suggest to take a look at the PNG format settings and sizes. Use the screenshot feature and then save your files with the same settings.
