### ISSUE TITLE
Artwork/Covers crashes emulator

### ISSUE THREAD

**Issue by Batchicken** [dborth/snes9xgx#696]
I am trying to have snes9xgx show artwork when I select a game, but as soon as the game is highlighted in the menu, the entire emulator crashes to the "Exception (DSI) occurred!" screen. I can't figure out how to get this to work correctly. Any help would be greatly appreciated!

**Comment by bladeoner** [comment]
I build a new version thanks to Qwertymodo who included MSU1 stream and BPS soft-patching support 4.3.8, could you give it a try?

https://github.com/dborth/snes9xgx/files/1601017/SNES9X.GX.4.3.8.zip

**Comment by dborth** [comment]
Seems to work fine for me with the latest codebase. Perhaps there's some compatibility issue with the files you're trying to use. I'd suggest to take a look at the PNG format settings and sizes. Use the screenshot feature and then save your files with the same settings.
