### ISSUE TITLE
Audio issues with PAL games in original and filtered modes

### ISSUE THREAD

**Issue by Wuerfel21** [dborth/snes9xgx#697]
Playing PAL games in the Original and  Filtered modes produces noticable audio cracks. Strangely, the chosen filter seems to affect this, even in original mode (but the filter has no effect!)! (I tried playing the german version of Secret of Mana)

**Comment by Wuerfel21** [comment]
EDIT: I just went back and checked, it is also there in unfiltered mode! (Oh, and i can't reproduce the effects of setting the filter... memory must have been faulty). But I managed to gather the NTSC version of SoM, which has no issues at all! (Except that it isn't in german...)

**Comment by askotx** [comment]
Or you could try NTSC patch version of that rom from romhacking:
http://www.romhacking.net/hacks/3352/

**Comment by Wuerfel21** [comment]
Thanks! I was looking for something like that, but I couldn't find anything!
