### ISSUE TITLE
Possibility Of Adding or Changing Filtering Options

### ISSUE THREAD

**Issue by WiiObsessive** [dborth/snes9xgx#698]
Hi, This is really more of a feature request, in line with the issue "Resolution #694".

I was noticing in snes9xgx along with fcegx and vbagx that the filtering modes are quite fuzzy, in (vbagx regardless of "bold" or "soft")

I've been using mGBA Wii for some GBA games because it can play some games more smoothly than vbagx, anyway, it has a filtering mode labeled "Bilinear Pixelated" which preserves the appearance of a sharp pixel perfect image while allowing for stretching that would, in an unfiltered mode look terrible.

Is it possible to add this as a filtering mode, or possibly the default filtering mode in snes9xgx (as well as others, I understand this is the issue thread for snes9x of course)?

I use 16:9 Correction with the horizontal resolution set to 85% to get an accurate aspect ratio, and this filtering mode would help greatly.

Thank you for your time.

**Comment by dborth** [comment]
Sounds like a good idea. But someone would need to code it. If someone does and submits a pull request, then I'll add it!
