### ISSUE TITLE
Robocop Vs Terminator game doesn't work well

### ISSUE THREAD

**Issue by SieKensou** [dborth/snes9xgx#699]
I tested this game and i works bad, it constantly flashes the screen.

**Comment by bladeoner** [comment]
Hi, which version did you use of SNES9x GX?

And is it on the WII of GC?

**Comment by askotx** [comment]
PR's are welcome and please this is not a forum, it's an issue tracker

**Comment by SieKensou** [comment]
Hi,
I used the last version that I can download from here "4.3.7 - December 8, 2016" for the Wii. But why is this closed? This is a problem of the emulator with this game, it doesn't run like that in the original Super Nintendo hardware but when I try to play it in this emulator for the Wii the screen is flashing constantly making the gameplay annoying :(

**Comment by askotx** [comment]
If you want to fix it, do it and make a pull request to submit that fix, thanks!

**Comment by SieKensou** [comment]
I think there is no need to be rude... obviously if I knew how to fix this issue I would do it and submit the fix instead of asking about that problem...

**Comment by dborth** [comment]
[Snes9xGX-4.3.8-Beta.zip](https://github.com/dborth/snes9xgx/files/2281405/Snes9xGX-4.3.8-Beta.zip)

Here's a beta to try out. This game is working in it. Please test as much as you can (and as many games as you can) and report back anything that was working before and isn't anymore.

**Comment by SieKensou** [comment]
Tested and now the game works. Thank you very much for this fix! I tried some other games and seems to work fine. I will let you know if I found any other issue with some other games.
Congratulations for the great job you are doing with this emulator.

P.S.: It would be great if you could put the latest revision of the emulator already compiled in a new folder for people to download it. Some people can't compile it correctly and others just don't know how. I'm sure it would be very helpful for a lot of people.
