### ISSUE TITLE
Delay with classic controller on old Wii model

### ISSUE THREAD

**Issue by DennisAppDevelopers** [dborth/snes9xgx#701]
there is a large delay if i use my classic Controller if i use only the wii-mote all is fine

**Comment by bladeoner** [comment]
Hi, which version did you use of SNES9x GX?

**Comment by DennisAppDevelopers** [comment]
the latest one for the homebrew channel

**Comment by DennisAppDevelopers** [comment]
v 4.3.7

**Comment by bladeoner** [comment]
Ok, I build a new version thanks to Qwertymodo who included MSU1 stream and BPS soft-patching support 4.3.8.

I don't believe it will fix your issue but it could be a compiling issue, so it's worth to try.

I will include the files here: [Uploading SNES9X GX 4.3.8.zip…]()

**Comment by DennisAppDevelopers** [comment]
i will try it today

**Comment by DennisAppDevelopers** [comment]
i think the problem is another one...i use by default only PAL games (50Hz) and the Timing to read the Controller is also different from 60Hz games i think.
and there is also another Problem, the Sound is running faster and the timer in supermario all stars is very fast.
if i compare it with the original all stars game on wii released on 20th anniversary on wii.

please take a look on it, there is something broken you can test NTSC supermario all stars  and PAL supermario all stars game
(the main Problem is the Timing in the PAL games i think )

**Comment by bladeoner** [comment]
Are you able to compile the source? Otherwise I would suggest to compile the source in the Pull Request I made.

I reverted the commit in 4.3.2 which changed something in the gamepad code.

**Comment by DennisAppDevelopers** [comment]
what do i Need to compile this Code? i compiled the snes-gx gamecube version and added zip-save-state in the past.
is it possible that there is a Problem if i run my Wii on 60Hz mode and start an homebrew channel Emulator which is running games in 50hz mode? i think if i run the old snes-gx gamecube Emulator the games are running more smoothly not only the controller-Input.

thx for ur help i love this emulator

**Comment by askotx** [comment]
Please, this is not a forum, it's an issue tracker, PR's are welcome
