### ISSUE TITLE
Switching between h2qx to scanlines causes mangled image

### ISSUE THREAD

**Issue by Klauserus** [dborth/snes9xgx#702]
hi.

i find a bug, i think. When i start a Game (GoofTroop for example) with filter: hq2x or hq2x bold and changed then in scanlines, it looks like the picture.

thank your for this great app. i hoped i cann help

<a href="http://www.bilder-upload.eu/show.php?file=b79f36-1503417501.jpg" target="_blank"><img src="http://www.bilder-upload.eu/thumb/b79f36-1503417501.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by bladeoner** [comment]
Hi, which version did you use of SNES9x GX?

**Comment by bladeoner** [comment]
I build a new version thanks to Qwertymodo who included MSU1 stream and BPS soft-patching support 4.3.8, could you give it a try?

SNES9X GX 4.3.8.zip

**Comment by Klauserus** [comment]
hi. thank you for working on it. I tested that yesterday. I can switch the filters from none to hq/hq2x = all good. But when i use scanlines and switch to none filter = same Problem like the picture in the post before

PS: it is Wii

**Comment by bladeoner** [comment]
I was able to reproduce the problem, could you please try the new 4.3.8 dborth released today and see if that fixed the issue?

The new version can be found here under Assets: https://github.com/dborth/snes9xgx/releases

**Comment by supersonicjc** [comment]
i honestly ran into this bug, the way I did it on the brand new v4.3.8 was I was looking at the different filters and went on each one at a time but then got to scanlines and it gives me a crash of all 3 which goes away once you turn the filters off and yet remains when you go to a new game, hope that helps if the other user isn't on here anymore

**Comment by dborth** [comment]
This is fixed in latest git.
