### ISSUE TITLE
(Request) WiiU Gamepad Support

### ISSUE THREAD

**Issue by tatundria** [dborth/snes9xgx#703]
Hi, it's recently become possible to add WiiU Gamepad support to vWii Emulators/Homebrew via WiiVC.
Could you add Fix94's Gamepad patch to your Emulators please?

https://github.com/FIX94/libwiidrc
from fix's readme:

libwiidrc

This is only usable with a sepcial patched fw.img and homebrew injected into a wiiu vc title, details on the patches are below.
The usage is quite simple, call WiiDRC_Init on boot and after that call WiiDRC_ScanPads every time you update your pad inputs.
See the "demo" folder for an example on how to use it in a bit more detail.
Both compiled Library and Demo can be grabbed from the Releases tab.

**Comment by askotx** [comment]
Duplicated issue

**Comment by saulfabregwiivc** [comment]
Hey there, i'm gonna ask if Snes9x GX is compatible with the Wii U GamePad?
