### ISSUE TITLE
No working GameCube releases after version 4.3.2

### ISSUE THREAD

**Issue by boktai1000** [dborth/snes9xgx#704]
It appears that builds for GameCube have stopped after the 4.3.2 release. I did try booting the .DOL file on my GameCube using SWISS of version 4.3.2 but had no such luck.

**Comment by bladeoner** [comment]
Hi, do you get an error message or something or it just didn’t start?

I’m busy with an unofficial 4.3.8 I think it has something to so with the change in 4.3.2 ‘Fixed lag with gamecube controllers’. I will see if I can revert that change and make a dol for you later.

**Comment by boktai1000** [comment]
Hi @bladeoner , I can test again to reconfirm but I believe there was no error message at all, otherwise I would have included it in my post for more detailed information. If I recall correctly, the screen just goes black and I have to manually reset the GameCube.

**Comment by bladeoner** [comment]
@boktai1000, I just revert the changes which were made in 4.3.2 and made a new build 4.3.8.
This build also includes BSP soft-patchting and MSU1 support.

I'm not able to test it myself, I don't own a GameCube.

Can you try to see if it works?

[SNES9X_GX_4.3.8_GameCube.zip](https://github.com/dborth/snes9xgx/files/1601167/SNES9X_GX_4.3.8_GameCube.zip)

**Comment by boktai1000** [comment]
@bladeoner 

I'll be trying it tonight and will report back. Thanks!

**Comment by boktai1000** [comment]
@bladeoner 

This build that you posted did indeed work on the GameCube, and I tested loading it with two versions of SWISS to be sure, one of them was the current latest (r431).

There is another - you could say, unrelated issue with GameCube DOLs and it's how the Exit functionality is handled. It will essentially just crash, since it doesn't seem to know how to return to SWISS. The best compromise is to configure it in the settings to Reboot. Honestly for GameCube releases, if Exit isn't possible - Reboot should probably be the only option. I should probably open a separate issue for this the more I think about it to be honest.

Anyways, that's an aside, but thought I'd mention if you were building a GameCube compatible / optimized release. But at the very least I can say, that your build does boot and work!

**Comment by bladeoner** [comment]
@boktai1000 glad it worked out for you, please proceed closing this issue and open a new one for the other issue.

**Comment by bladeoner** [comment]
@askotx can you please close this issue since it has been resolved and look at my PR?

Thanks in advance.

**Comment by boktai1000** [comment]
@bladeoner sorry for the delay in closing this, but I also wanted to mention that I believe the reason why I wasn't able to get subsiquent releases to work may be due to the fact that there was no GameCube compiled version so using the compiled versions from https://github.com/dborth/snes9xgx/releases were likely only compatible with the Wii. Regardless your compiled version worked as I mentioned above, but I wanted to follow up with this comment as I had more time to analyze and see what may have been going wrong.

I also tested MSU compatibility which appeared to work and I really appreciate having the functionality on GameCube, but I feel like more information regarding MSU probably deserves it's own separate discussion. Anyways - thank you for your work, and I hope this helps regarding your development for Snes9xGX
