### ISSUE TITLE
Mayflash NES SNES to Wii WiiU adapter not fully compatible...?

### ISSUE THREAD

**Issue by littlebigboss12** [dborth/snes9xgx#705]
https://www.amazon.ca/Mayflash-NES-SNES-Controller-Adapter/dp/B00B2K0C8M

Got this with the hopes of using original NES and SNES controllers with FCEU GX and SNES9X GX, but it doesn't seem to function correctly. It recognized the SNES controllers as 'classic controllers' immediately but after a few seconds the emulator would skip frames erratically and the controller inputs would act as though they were being pressed when they weren't (this happens in the GUI menu for both emulators as well). 

This was tested with two different Mayflash adapters and two different (tested working fine) SNES controllers, and a Luigi Wiimote Plus on my WiiU vWii with Super Mario Bros. for FCEU GX and Star Fox and Super Mario World for SNES9X GX. 

I suspect the Mayflash adapters do something the emulators don't like, because as soon as I unplugged it from the Wiimote, everything worked as normal (framerate and controller response normal). Is there anything that can be done to fix this? I'll submit whatever information I can.

**Comment by bladeoner** [comment]
I build a new version thanks to Qwertymodo who included MSU1 stream and BPS soft-patching support 4.3.8, could you give it a try I don't know if it will solve your problem but it's worth a try.

https://github.com/dborth/snes9xgx/files/1601017/SNES9X.GX.4.3.8.zip

**Comment by littlebigboss12** [comment]
Hi @bladeoner that's really kind of you! I thought this was never going to get answered, and I ended up sending the adapters back to Amazon 3 weeks ago since I didn't want to be stuck with non-functional adapters and out $50CDN. I ended up getting these instead from here: 

http://www.raphnet-tech.com/products/ns64gc_to_wiimote/index.php

They also support N64 and GameCube controllers as classic controllers. I haven't tried them yet, so I'll let you know if they work without issue :D

**Comment by kinopravda** [comment]
Hi! 
So glad I've found someone with the same issue, and at the same time too.
I've got exactly the same problem as @littlebigboss12 describes. The emulator and controller inputs lag as hell. 

I updated with your patch @bladeoner, many thanks but the issue remains unsolved.

Without any knowledge of emulators' programming, a theory of mine is that the lag depends on the controller input. In Snes9X menu for button mapping, the emulator believes the mayflash adapter is a Wii Classic Controller as that's what it responds to, but the CC also have analog sticks which the SNES controller doesn't. Does the emulator believe my controllers' D-pad is the analog stick on the CC?

I have the exactly same issue while using an original NES controller for both Snes9X and FCEU.

Any help would be much appreciated.

**Comment by littlebigboss12** [comment]
Hey @kinopravda , did you try @bladeoner 's patched 4.3.8 SNES9X in the link he provided? I wish I could be more help at this point, but as I said, I gave up on the Mayflash...

**Comment by kinopravda** [comment]
Yes, I tried the patch with no luck. Same problem.

**Comment by littlebigboss12** [comment]
@kinopravda well that sucks. If you can still return your Mayflash adapters to wherever you bought them, I'd do that if I were you. You'd be much better off getting the raphnet adapters as I linked above, as they support more, although they are 2x the price :/

**Comment by bladeoner** [comment]
Are you able to compile the source? Otherwise I would suggest to compile the source in the Pull Request I made.

I reverted the commit in 4.3.2 which changed something in the gamepad code.

**Comment by Cobrabee** [comment]
I would really be psyched to see this issue finally addressed. For those unfamiliar with this piece of hardware, it is an adapter that is sold as a NES/SNES to Wii Remote input, that should function as an official Classic Controller. Off-label, the NES input in run through a dongle that, when removed, reveals a 9-pin input that can accept Gen/MD, Atari, C64, etc. controllers. So for Wii emulation, it is physically capable of allowing users the ability to have the feeling of the original controller for quite a few of the systems emulated on the system. It works 100% with all official Wii VC games, but creates delayed (at best) input on every emulator I have tried. At this point, I am intellectually curious as to why a piece of hardware with no input lag for official titles gives consistent problems with homebrew; is this indicative of a different protocol in common homebrew dev kits that could be made more accurate across projects?

**Comment by dborth** [comment]
If someone submits a pull request with the changes, then I'll add it.
