### ISSUE TITLE
Comile error: MAXPATHLEN was not declared in this scope

### ISSUE THREAD

**Issue by kshade** [dborth/snes9xgx#706]
I think I've followed the instructions on the wiki, and my devkit installation can at least compile the example code it comes with. When I'm trying to compile snes9xgx though, this happens in both Linux and Windows:

```
cheatmgr.cpp
In file included from c:/devkitPro/msys/home/user/snes9xgx-4.3.7/snes9xgx-4.3.7/source/cheatmgr.cpp:15:0:
c:/devkitPro/msys/home/user/snes9xgx-4.3.7/snes9xgx-4.3.7/source/snes9xgx.h:87:18: error: 'MAXPATHLEN' was not declared in this scope
  char LoadFolder[MAXPATHLEN];  // Path to game files
```

I've tried fixing the issue by adding the appropriate includes, but that only led to more errors. I think I might be missing a step?

**Comment by bladeoner** [comment]
After a lot of trying on error I found out it has something to do with using the latest DevKit.
Use the one that I attached and you should be find, I also made a Readme file with instructions to get it installed.
[devkitPro.zip](https://github.com/dborth/snes9xgx/files/1593175/devkitPro.zip)

**Comment by kshade** [comment]
Thank you, the download you linked just seems to install the current Devkit version though? I've replaced the PPC devkit folder with version r24 and those errors are gone now, but linking still fails with

`linking ... snes9xgx-wii.elf
c:/devkitPro/portlibs/ppc/lib\libmxml.a(mxml-file.o): In function `mxml_get_entity':
mxml-file.c:(.text+0x400): undefined reference to `__locale_ctype_ptr'
c:/devkitPro/portlibs/ppc/lib\libmxml.a(mxml-string.o): In function `_mxml_vsnprintf':
mxml-string.c:(.text+0x33c): undefined reference to `__locale_ctype_ptr'
mxml-string.c:(.text+0x3a0): undefined reference to `__locale_ctype_ptr'
collect2: ld returned 1 exit status
make[2]: *** [/home/user/snes9xgx-4.3.7/executables/snes9xgx-wii.elf] Error 1
make[1]: *** [build_wii] Error 2
make[1]: Leaving directory `/home/user/snes9xgx-4.3.7'
make: *** [wii] Error 2`

There is no older libmxml available it seems.

**Comment by kshade** [comment]
Found an older version (as in, compiled in 2010, it's still version 2.6) of mxml and it worked! Thanks for your help and happy new year.

**Comment by bladeoner** [comment]
Glad it worked out, happy to help! :)

About the zip I attached:
You install: DevKitProUpdate 1.6.0 
- In: c:\devkitpro
- Then you delete the c:\devkitpro\devkitppc\ folder.
- Then you install the included devkitppc r26, at this moment is the best version in c:\devkitpro\
- And you delete any portlibs and libogc folder in c:\devkitpro\
- After that you copy the included portlibc and libogc folder to c:\devkitpro\ and you should be ready to go.

**Comment by kshade** [comment]
Oh, I see, okay, ended up doing pretty much that, except I went with a slightly older devkitppc. Thanks again!
