### ISSUE TITLE
When does a new version of Snes9x gx appear for the Wii? (2018)

### ISSUE THREAD

**Issue by cokeflash** [dborth/snes9xgx#712]
When does a new version of Snes9x gx appear for the Wii?

Other graphics filters (hi-resolution) would be good :-)

**Comment by roflcopter777** [comment]
I suggest alternatives like RetroArch in the mean time

**Comment by cokeflash** [comment]
ok

**Comment by R-S1** [comment]
Hello I am wondering the same thing as well but a version that will include compatibility with Hyperkin's SNES adapter + SNES Mouse. Both can be hooked up to a Wii remote but the emulator doesn't support using a classic controller to mimic a SNES mouse. Which is probably enough to fix the issue or it needs to be properly implemented to support the accessories I am suggesting. I just tested both a few minutes ago so I am hoping for a quick reply is possible.

**Comment by Nashismo** [comment]
Retroarch snes9x cores are good, BUT are no way near as fast as this port of Snes9x. Games like Yoshi Island and toher Super FX games play at fullspeed in Snes9x GX, on retroarch? No way in hell.

Cheers, and I am also hoping for a new version with a few new features, mainly, a more refined Vsync to fix some sound issues.

**Comment by bladeoner** [comment]
@cokeflash @Nashismo [Snes9x.GX.New.zip](https://github.com/dborth/snes9xgx/files/2239028/Snes9x.GX.New.zip)

**Comment by Nashismo** [comment]
Thank you so much bladeoner!! I will be trying this new version and will be posting my discoveries. Thanks again, you are awesome bladeoner.
