### ISSUE TITLE
Unable to compile latest commit

### ISSUE THREAD

**Issue by RandomMan25XX** [dborth/snes9xgx#713]
When trying to compile the latest commit it complains of msu1.h missing from the source and then stops, any idea as to where this file would be located?, because I'd like to compile the latest commit

**Comment by RandomMan25XX** [comment]
now it's another issue:
> "make" 
"make" -f Makefile.wii
make[1]: Entering directory `/c/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master'
audio.cpp
cheatmgr.cpp
In file included from c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/cheatmgr.cpp:15:0:
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:87:18: error: 'MAXPATHLEN' was not declared in this scope
  char LoadFolder[MAXPATHLEN];  // Path to game files
                  ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:88:22: error: 'MAXPATHLEN' was not declared in this scope
  char LastFileLoaded[MAXPATHLEN]; //Last file loaded filename
                      ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:89:18: error: 'MAXPATHLEN' was not declared in this scope
  char SaveFolder[MAXPATHLEN];  // Path to save files
                  ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:90:19: error: 'MAXPATHLEN' was not declared in this scope
  char CheatFolder[MAXPATHLEN];  // Path to cheat files
                   ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:91:25: error: 'MAXPATHLEN' was not declared in this scope
  char ScreenshotsFolder[MAXPATHLEN]; //Path to screenshots files
                         ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:92:19: error: 'MAXPATHLEN' was not declared in this scope
  char CoverFolder[MAXPATHLEN];  //Path to cover files
                   ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:93:21: error: 'MAXPATHLEN' was not declared in this scope
  char ArtworkFolder[MAXPATHLEN];  //Path to artwork files
                     ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:94:20: error: 'MAXPATHLEN' was not declared in this scope
  char  ImageFolder[MAXPATHLEN];  //Saved image folder path
                    ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/snes9xgx.h:96:21: error: 'MAXPATHLEN' was not declared in this scope
  char Exit_Dol_File[MAXPATHLEN]; // Exit Path
                     ^~~~~~~~~~
In file included from c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/cheatmgr.cpp:17:0:
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/filebrowser.h:29:11: error: 'MAXPATHLEN' was not declared in this scope
  char dir[MAXPATHLEN + 1]; // directory path of browserList
           ^~~~~~~~~~
c:/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master/source/filebrowser.h:61:20: error: 'MAXPATHLEN' was not declared in this scope
 extern char szname[MAXPATHLEN];
                    ^~~~~~~~~~
make[2]: *** [cheatmgr.o] Error 1
make[1]: *** [build_wii] Error 2
make[1]: Leaving directory `/c/Users/mmoye/Downloads/3ds-CIAs/wii/snes9xgx-master'
"make": *** [wii] Error 2

**Comment by bladeoner** [comment]
See my Pull Request for the missing msu1 files.

See the following closed issue for the second problem:
Comile error: MAXPATHLEN was not declared in this scope #706

**Comment by bladeoner** [comment]
@RandomMan25XX [Snes9x.GX.New.zip](https://github.com/dborth/snes9xgx/files/2239025/Snes9x.GX.New.zip)

**Comment by dborth** [comment]
Use the latest devkitPPC and portlibs. The latest commit will work with them.
