### ISSUE TITLE
Graphic glitch with Hook game

### ISSUE THREAD

**Issue by cecilmax** [dborth/snes9xgx#714]
Thereis graphic glitches when playing Hook, in the cutscenes the text is followed by Q character floating just behind each letter of the text.

I read somewhere this can be fixe with disable the allowinvalidvramacces.

Can you tell me where in the source I can disable it ? Thanks :)

**Comment by dborth** [comment]
preferences.cpp line 477.

Settings.BlockInvalidVRAMAccess = false;
