### ISSUE TITLE
Cannot compile it with mxml 2.11

### ISSUE THREAD

**Issue by cecilmax** [dborth/snes9xgx#715]
Hi, I want to compile it with last version of mxml 2.11 but it doesnt work. How can I compile mxml to work with snes  
9x gx source ? Thanks :)

**Comment by bladeoner** [comment]
Mxml 2.11 requires a newer dekvkit version like r29.1, compiling snes9x version r24 or r26 with the mxml from that time.

See the following closed issue for the correct files: 
Comile error: MAXPATHLEN was not declared in this scope #706

**Comment by dborth** [comment]
Use the latest devkitPPC + portlibs. It all works together.
