### ISSUE TITLE
Exit doesn't close properly on GameCube compiled version

### ISSUE THREAD

**Issue by boktai1000** [dborth/snes9xgx#717]
When you attempt to use the Exit button in the application on the GameCube version, it simply results in the application to crash and having to get up and manually reboot your GameCube. I'm launching the application with Swiss, and would expect to be returned to Swiss - but I imagine that may not be possible due to how the GameCube launches and executes in comparison to the Wii.

Regardless the workaround that I've found is just changing the Exit functionality to Reboot, which can be configured in the settings menu. Not as quick as one would hope, but it does the trick. Regardless, it would be nice to either make this the default and only functionality for the GameCube compiled version as opposed to having a broken Exit that just crashes, or if it is possible to return to Swiss somehow that would be great.

Thanks!

**Comment by dborth** [comment]
Not sure what the best solution here is as I don't use the GameCube version myself. I'd suggest poking emukidid. If he can supply or suggest the changes (pull request or otherwise) I'll add it.
