### ISSUE TITLE
Feature Request - Support for Hyperkin's Mouse & Adapter

### ISSUE THREAD

**Issue by R-S1** [dborth/snes9xgx#718]
Hello, I just recently took the dive and bought these two peripherals from the Hyperkin brand.
[Hyper Click Retro Style Mouse for SNES](https://www.walmart.com/ip/Hyperkin-Hyper-Click-Retro-Style-Mouse-for-SNES-Gray/581485529?wmlspartner=wlpa&selectedSellerId=0&adid=22222222227093023093&wmlspartner=wmtlabs&wl0=&wl1=g&wl2=c&wl3=207502360539&wl4=aud-306997118081:pla-360544529714&wl5=9031362&wl6=&wl7=&wl8=&wl9=pla&wl10=8175035&wl11=online&wl12=581485529&wl13=&veh=sem)
[Hyperkin Controller Adapter for SNES](https://www.walmart.com/ip/Hyperkin-Hyperkin-Controller-Adapter-for-SNES-to-SNES-Classic-Black/230158833?wmlspartner=wlpa&selectedSellerId=0&adid=22222222227000000000&wl0=&wl1=g&wl2=c&wl3=42423897272&wl4=aud-310687321802:pla-51320962143&wl5=9031362&wl6=&wl7=&wl8=&wl9=pla&wl10=8175035&wl11=online&wl12=230158833&wl13=&veh=sem)

The mouse was made for an actual SNES while the adapter was made for the SNES classic. But one can connect the mouse to the adapter then connect said adapter to a Wii Remote. Theoretically, the emulator should read the connection as a classic controller. I tried this out with the latest SNES9GX release but to my dismay. The emulator does not support a classic controller to mimic a SNES mouse in the first place. If a classic controller were supported as a mouse I would at least expect the buttons on the mouse to make some response but as to movement. I believe extra work would have to be done as well. I tried this out on RetroArch with the SNES9X 2010 core as well. But no button or movement response except when I connected the adapter to the Wii Remote RetroArch would recognize the connection as if I had connected a classic controller. If anyone could look in to this I would very much appreciate the help, thanks.

**Comment by dborth** [comment]
Sounds like a good idea. If someone submits a pull request I'll take a look. But this isn't the place to ask for features.
