### ISSUE TITLE
Bug on sound, latest versions of snes9x gx, nintendo wii

### ISSUE THREAD

**Issue by spielvan** [dborth/snes9xgx#727]
Hello, a friend asked to report a bug that occurs with him in the latest versions of snes9x gx from nintendo wii: could I fix the audio problem, which appeared after version 4.2.9 on nintendo wii, I use this version until today cause of the problem of later versions, the problem is that sometimes it gives a few snaps, a game that I remember that gives this problem is the cybernator, just watch the opening with headphones that will give to realize.

**Comment by bladeoner** [comment]
@spielvan [Snes9x.GX.New.zip](https://github.com/dborth/snes9xgx/files/2239023/Snes9x.GX.New.zip)

**Comment by bladeoner** [comment]
Did the new version fix your problem?

**Comment by spielvan** [comment]
Hi all, I gave the file to his friend to test, so he was just going to be able to test it this weekend, but I sent him a message, asking him how it was, as soon as he answers I'll say thank you.

**Comment by spielvan** [comment]
@bladeoner  My friend tested and I also tested, the new snes9 gx 4.1.1, and it is very clear the clicks in the audio of the game, we tested with 2 games: in the cybernator during the opening, and in J. League 96 dream stadium, during the match.

**Comment by dborth** [comment]
Here's a beta, maybe it's better?
[Snes9xGX-4.3.8-Beta2.zip](https://github.com/dborth/snes9xgx/files/2285356/Snes9xGX-4.3.8-Beta2.zip)

**Comment by dborth** [comment]
[Snes9xGX-4.3.8-Beta3.zip](https://github.com/dborth/snes9xgx/files/2287922/Snes9xGX-4.3.8-Beta3.zip)

Here's another beta. Hopefully this is at least as good as the last if not better. Let me know.

**Comment by dborth** [comment]
[Snes9xGX-4.3.8-Beta4.zip](https://github.com/dborth/snes9xgx/files/2288514/Snes9xGX-4.3.8-Beta4.zip)

Here's another beta.
