### ISSUE TITLE
Commit "Fix compilation errors with latest libOGC/devkitPPC" breaks compiling

### ISSUE THREAD

**Issue by bladeoner** [dborth/snes9xgx#729]
When I try to compile the latest Master I'm getting errors on compiling, it seems that after commit "Fix compilation errors with latest libOGC/devkitPPC" things are broken:

make -f Makefile.wii
make[1]: Map '/c/devkitpro/examples/snes9xgx-master' entered
snes9xgx.cpp
C:/devkitpro/examples/snes9xgx-master/source/snes9xgx.cpp: In function 'int main(int, char**)':
C:/devkitpro/examples/snes9xgx-master/source/snes9xgx.cpp:405:23: error: invalid conversion from 'void ()()' to 'resetcallback' {aka 'void ()(long unsigned int, void*)'} [-fpermissive]
SYS_SetResetCallback(ResetCB);
^~~~~~~
In file included from C:/devkitPro/libogc/include/gccore.h:62,
from C:/devkitpro/examples/snes9xgx-master/source/snes9xgx.cpp:14:
C:/devkitPro/libogc/include/ogc/system.h:325:50: note: initializing argument 1 of 'void (* SYS_SetResetCallback(resetcallback))(u32, void*)'
resetcallback SYS_SetResetCallback(resetcallback cb);
^
C:/devkitpro/examples/snes9xgx-master/source/snes9xgx.cpp:493:20: warning: format '%x' expects argument of type 'unsigned int*', but argument 3 has type 'u32*' {aka 'long unsigned int*'} [-Wformat=]
sscanf(argv[4], "%08x", &GCSettings.Exit_Channel[0]);
^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/devkitpro/examples/snes9xgx-master/source/snes9xgx.cpp:494:20: warning: format '%x' expects argument of type 'unsigned int*', but argument 3 has type 'u32*' {aka 'long unsigned int*'} [-Wformat=]
sscanf(argv[5], "%08x", &GCSettings.Exit_Channel[1]);
^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [/opt/devkitpro/devkitPPC/base_rules:13: snes9xgx.o] Error 1
make[1]: *** [Makefile.wii:109: build_wii] Error 2
make[1]: Map '/c/devkitpro/examples/snes9xgx-master' exit
make: *** [Makefile:10: wii] Error 2

**Comment by dborth** [comment]
The latest commit fixes this. Note that although it compiles, I get a mysterious crash when the wiimote connects in the wiiuse handshake in __lwp_wkspace_free

Oddly enough, just NOT using the latest freetype portlib fixes that. I'm open to suggestions!
