### ISSUE TITLE
Turbo speed causes audio to mute

### ISSUE THREAD

**Issue by supersonicjc** [dborth/snes9xgx#737]
so I picked up the brand new complied v4.3.8 and tried it out, when I go to use the speed up option using my right control stick on the wii the game will mute the music and it requires me to hit the stick a few times before any audio returns, not 100% sure if this is intended or if this is a new bug as honestly feels like a bug with the audio tweeks that took place

**Comment by dborth** [comment]
Yes, I saw this as well. But as you said if you jiggle the stick it comes back.

I looked into it and I don't know how to fix it. Maybe someone else will be able to track it down.

**Comment by dborth** [comment]
this is fixed.
