### ISSUE TITLE
SNES9X GX Screenshots

### ISSUE THREAD

**Issue by fancymelonub** [dborth/snes9xgx#739]
I have SNES9X GX 4.3.8 on my USB.

For some reason, screenshots don't work. I don't know why, can it be because it's on a USB instead of SD?
Also, the audio is fully cutted out of gameplay until I restart the game, even after turning off fast-foward.

**Comment by dborth** [comment]
No idea why screenshots aren't working for you. The audio issues will be fixed in the next version.
