### ISSUE TITLE
Error having many covers

### ISSUE THREAD

**Issue by alberto8192** [dborth/snes9xgx#748]
When I have many covers on the game selection screen, the emulator gives an error and crashes. The screen stays black with white letters. Any solution?

**Comment by supersonicjc** [comment]
i had that issue a while ago when they first made the box covers a thing, then I made the snaps smaller in size and around the sizing of 320-240 for snes and 240-320 for sfc titles depending on the actual box and tend to find those sizes decent without making them look grainy or bad, if I made them bigger then that ie 640-480 I would find the emu crashing, that or is there something else going on there?? also format of .png well it wasn't a great format it works for this

**Comment by alberto8192** [comment]
I have difficulties to understand the English language. I am from Spain. I
use the covers in png 316x224 format and when I have many and I navigate
quickly in the menu, the emulator is paralyzed. The only solution I could
think of was to create a different folder for each game because having more
than 8 or 10 games in the same folder will paralyze the emulator when
navigating through it.
