### ISSUE TITLE
snapshots get listed out of order when there's more than 9, plus improved sorting in UI idea

### ISSUE THREAD

**Issue by randomname42** [dborth/snes9xgx#749]
When you bring up the menu (load, save, or delete) and you have more than 9 snapshots, the snapshots get listed out of order. I think the problem is that Snes9xgx lists snapshots by first digit of the number, not in the order of the whole number. 

In other words, what I think is happening is you'll see snapshot 1, then snapshots 10, 11, 12, etc, then snapshot 2.

I believe vbagx has this same behavior too. Should I post the issue there too, or is here enough?

A couple other suggestions to make the ui just a little more convenient :
Show the snapshot's number after where it says "snapshot" 
Ability to sort in the menu by either number (like it is now, but with fixed sorting above 9), or date made.

**Comment by dborth** [comment]
These are good ideas. If someone does them and submits a PR, I'll certainly merge it.
