### ISSUE TITLE
SNES Mouse controls

### ISSUE THREAD

**Issue by stubl** [dborth/snes9xgx#758]
I use different controls in snes9xgx but the SNES Mouse always seems restricted on screeen in snes9xgx with both wiimote and GameCube controller, it would be good if the SNES Mouse could move as freely across the screen as the Justifier and Superscope controls

**Comment by dborth** [comment]
Unfortunately the mouse doesn't work the same way on the SNES as the justifier / superscope. You can't provide it specific coordinates to move the mouse to. So this was as good as I could get it...which is actually kinda close to how I remember the original mouse working (or not working!) - it was always a little frustrating!
