### ISSUE TITLE
Player 2 controller input in snes9xgx

### ISSUE THREAD

**Issue by vrmax81** [dborth/snes9xgx#803]
I was looking at possible other issues that were closed and the only one that came across as being the same issue is 533. I cannot use controller 2 with the classic controller plugged in, and the classic controller I have plugged in is a modified original SNES controller to plug into the wii remote. I can press the start button on the player 2 classic controller but when I try to configure only controller 2 button mappings I can only use controller 1 classic controller to do this. I was also wondering since the person that looked into the 533 issue said everything was fine and listed his setup. I have not checked that to see if it matches but would the ios 202 be a possible issue for this? Again I cannot use the controller not even just the wii remote as player 2 but can press enter like in final fight I can press enter to get to the character selection screen.

**Comment by dborth** [comment]
I tested this, it works perfectly fine for me. Perhaps try resyncing both remotes from outside of homebrew - in the Wii menu itself.
