### ISSUE TITLE
Font file not found

### ISSUE THREAD

**Issue by DDinghoya** [dborth/snes9xgx#807]
Thank you for your build! :)

When I tried to change language for Korean, no problem apply to Korean on Homebrew channel.

However, Snes9x's pop-up error massage "Font file not found!" on your attached channel.

Of cause I put ko.tff file into /apps/snes9x

Would you please review for this issue? 

VBA GX is same issue as Snes9x Gx and FCE Ultra GX is no problem.

**Comment by dborth** [comment]
I tried all 3 and they all work fine for me. Don't know what to tell you.

**Comment by DDinghoya** [comment]
> I tried all 3 and they all work fine for me. Don't know what to tell you.

I think this issue is create to settings.xml location for Snes9x GX and Vba GX as belows;

When I load Snes9x GX and Vba GX on homebrew 
: Create to root/snes9xgx and root/vbagx

When I load Snes9x GX and Vba GX on channel forward
:  Create to root/apps/snes9xgx, root/apps/vbagx

Therefore in my case, It seems not search "settings.xml" that an error has occurred loading on the channel forwarder, after loading on the homebrew channel

Anyway This issue has been fixed by move "settings.xml" from root/xxx to root/apps/xxx.
