### ISSUE TITLE
vWii Controller Issues 

### ISSUE THREAD

**Issue by kingdwemen** [dborth/snes9xgx#809]
Hi, I have an issue trying to use certain controllers in Snes9x GX on the vWii of the Wii U. Specifically, I'm having a frustrating time trying to sync controllers to Snes9x GX in the order that I want them to sync.

I want to use the Wii U Pro Controller in the emulator, but my Wiimote is always synced as Controller 1 (The first LED is lit) as I start the homebrew (It's the only way to navigate the Homebrew Channel). Snes9x GX makes it so that the first controller synced is the controller plugged into the first controller port once emulation starts, and I can't find a way to change the controller order inside the emulator itself, so I'm stuck using the Wiimote to play games.

I've tried syncing the Pro Controller before the Wiimote is turned on (The LED's on the Wiimote shut off for a few seconds when launching the emulator), but no matter what the Wiimote is always picked up as Controller 1, and the Pro Controller as Controller 2 (The second LED is lit). I can't find any way to change the order they're synced on the vWii side of things as the Pro Controller can't be turned on anywhere else *but* the homebrew that supports it. 

The ONLY way I've gotten Snes9x GX to use the Pro Controller first is through the Wii U side: By syncing the Pro Controller before any Wiimotes (You can use the Pro Controller to navigate Wii U menus, but you have to sync a Wiimote and use it to press the screen options when you try to launch the vWii), the Pro Controller is read as Controller 1 as you enter the vWii. Even when the controller is shut off, all synced Wiimotes are synced as Controller 2, 3, 4 etc. Thus, I can use the Pro Controller as Controller 1 in the homebrew that supports it. This is a very roundabout method to get it working however, and not very convenient (and as it affects the whole of the vWii side, I could see issues where the Wiimote being synced as Controller 2 would be less ideal, like for NES emulators or Gameboy emulators where features of the Wiimote or its button layout would be more preferred).

As I can still use the controller as intended, I'm not sure if it could be considered an issue, but I think it would be much better if a person could change the controller order inside the emulator so you could use any controller that's synced as Controller 1. To me, it would be much more convenient than having to fiddle with the order that controllers are synced.

**Comment by dborth** [comment]
I hear your pain, but unfortunately this is really an issue with the underlying library, wiiuse, which is a part of libogc. There's nothing I can do.
