### ISSUE TITLE
Custom background music not working.

### ISSUE THREAD

**Issue by mepozuzak** [dborth/snes9xgx#812]
I'm using an original Gamecube with a SD-card and Action Replay bootdisk.

I liked the background music from the Nintendo SNES mini so I found a mp3 and converted it into bg_music.ogg and placed it in the snes9xgx map. But there is no music when I start up snes9xgx.

I also tried it in FCE_Ultra_GX, also no music.

**Comment by askotx** [comment]
Load music files it's only for Wii.
