### ISSUE TITLE
Screenshots not displaying

### ISSUE THREAD

**Issue by mepozuzak** [dborth/snes9xgx#813]
I'm using an original Gamecube with a SD-card and Action Replay bootdisk.

The screenshot or cover art feature has never worked for me. I can make a screenshot in the menu and it creates a proper pgn screenshot on the sd card, but it wont display properly in the side bar (the screenshots in the snapshot saves do work).

Sometimes it doesn't diplay at all, sometime it's a weird pattern. I build a LED in the SD adapter so it lights up when something loads, and it does flicker so the emulator does do something.

FCE Ultra GX has the same problem, but Visual Boy Advance GX does work correct.

I uploaded two pictures how it sometimes looks.

[mirror]
https://ibb.co/nDpbRNM
https://ibb.co/8046Y9w

![img_0383](https://user-images.githubusercontent.com/47793457/53041804-28202200-3485-11e9-8b19-48bc455383ac.JPG)
![img_0384](https://user-images.githubusercontent.com/47793457/53041805-28b8b880-3485-11e9-9cb5-e8bd4acec736.JPG)

**Comment by dborth** [comment]
[fceugx-gc.zip](https://github.com/dborth/snes9xgx/files/2887398/fceugx-gc.zip)

Can you test this build and let me know if images work?

**Comment by mepozuzak** [comment]
I tested it but still the same problem. Sorry.

**Comment by dborth** [comment]
[fceugx-gc (2).zip](https://github.com/dborth/snes9xgx/files/2922477/fceugx-gc.2.zip)

Okay, one more try then. Does this work?

**Comment by pakitovic** [comment]
Hi! It's working now 

![photo_2019-03-02_22-42-04](https://user-images.githubusercontent.com/18547138/53687978-71e9f180-3d3c-11e9-9fee-4b3fa04353a4.jpg)

**Comment by dborth** [comment]
thanks for testing! closing.
