### ISSUE TITLE
request- text viewer

### ISSUE THREAD

**Issue by mepozuzak** [dborth/snes9xgx#815]
I don't know how emulators work, so this might be a dumb request but here goes.

Is it possible to add a text editor in the menu?
That way I don't have to use another computer to look up a walkthrough or look up the special moves in a fighter, or maybe some built in passwords and cheat codes.
About a month ago I was playing a rpg and I constantly had to look up on the internet an item list for stats of weapons and armor because in the game you could only see the stats when the item was equipped.

Gamefaq has text file walkthroughs so txt files could work just fine. A word search option and a way to bookmark a line would be great too.

Thank you for your time.

**Comment by askotx** [comment]
Yes, it's possible, but Pull Requests are welcome.
