### ISSUE TITLE
Tricky controller assignment 

### ISSUE THREAD

**Issue by garcimak** [dborth/snes9xgx#823]
Can't make WIIU/NGC gamepad the main controller by default, it connects as P2 and the wiimote wich is used to launch snes9x is P1.  Battery must be removed to get rid of the wiimote, controllers  assignment won't be saved for next launch.

**Comment by dborth** [comment]
This has been asked before. I'm not doing anything about this. If you remove your controllers from the Wii menu and readd them there in the order you want it works fine.
