### ISSUE TITLE
cheat code limit

### ISSUE THREAD

**Issue by supersonicjc** [dborth/snes9xgx#826]
so I was reading the info file that is on the site, it states that the limit for cheat codes is 150 codes, I was playing a game that I have more then 150 codes for and noticed the emulator cuts the file off at 100 codes, I tested using the official and the build you sent me, 2 games I have with code lists over 100 and once I hit that line the rest of the codes don't show up.
2 questions for this, is there a way to get it up to 150 and also possible to expand the limit as I have at least 3 games (JRPG's) that have huge lists of codes 
please and thank you for the hope that your able to increase the limit but if not at least get it so it goes to the 150 limit that is to be offered now

**Comment by bladeoner** [comment]
@supersonicjc please try this build https://gbatemp.net/attachments/snes9x-gx-4-4-2_test-zip.163033/ I tried to increase the codes from 100 to 150. I think more than 150 will make the emulator really slow or let it crash, so that is not something we want.
