### ISSUE TITLE
Suggestion for accurate FX Chip Speed (underclock)

### ISSUE THREAD

**Issue by Nashismo** [dborth/snes9xgx#832]
Hi, first thank you for your awesome job at porting this wonderfull emu.

So here is the thing, the emulator is reaching perfection, but there is one thing that keeps it from being the real thing; FX Speed is too fast.

I have tested Star Fox 1 on real hardware and on Snes9xGX (the latest version) and the game runs faster than it should on Snes9xGX.

Could there be a way to underclock the FX Chip? As we have the options to overclock the FX chip (which I dont recommend for accuracy) couldn't we have an option to underclock it?

Then everyone could test their underclocked settings and wether is accurate or not. Obvously I would test this extensively and could come up with the perfect speed (underclock options would have to be very minor 1/2/3/4mhz options of course)

My suspicion also is that the emu is emulating the FX Chip 2 that run at 20mhz or so, and Star Fox uses the FX Chip 1.

Nonetheless, it would be amazing if you could add this option! Or maybe I am asking too much and it is too difficult!

Thank you so much for listening and thank you for your time.

My best regards! 
Nashismo

**Comment by bladeoner** [comment]
Adding an option like that will break other games.

Which version did you use the latest 4.4.2 or did you build it yourself

**Comment by Nashismo** [comment]
> 
> 
> Adding an option like that will break other games.
> 
> Which version did you use the latest 4.4.2 or did you build it yourself

I am using 4.4.2 

But why would it break other games when overclocking doesn't?

Or maybe Star Fox runs too fast because of a timing issue? I am betting on that one. I mean for me overclocking the FX ship would be great if only timing was right... so that is way I was asking for downclocking, it "sounded like the most simple solution" (to fix bad timing is some games) as aiming for absolute accuracy requires more than what the Wii is capable of.

Again thank you, and if only as a test, I would be more than happy to test a Snes9xgx with downclocking, and I would test it with most FX compatible games checking original snes vs snes9xgx (don't have them all but I can manage).

Thank you, and if this is too difficult or you guys have already tried this, then is ok, I still thank you for your time.

My regards, Nashismo.

**Comment by bladeoner** [comment]
You could try my compiled version on, i update regularly it doesn't have the latest change yet:
https://gbatemp.net/threads/snes9x-gx-4-4-0-beta-feedback-requested.521929/

Direct link:
https://gbatemp.net/attachments/snes9x-gx-4-4-2-zip.162671/

**Comment by Nashismo** [comment]
> 
> 
> You could try my compiled version. I update regularly it doesn't have the latest change yet:
> https://gbatemp.net/threads/snes9x-gx-4-4-0-beta-feedback-requested.521929/
> 
> Direct link:
> https://gbatemp.net/attachments/snes9x-gx-4-4-2-zip.162671/
> 
> Just see if it work different, it contains a lot of changes which where added after 4.4.2

Wow thanks! I will try as soon as possible and will check if the speed varies a least in Star Fox and if the timing is a bit more accurate.

I will let you know, thanks again and for all your work.
Nashismo

**Comment by Nashismo** [comment]
Tested it. Is just as good as the 4.4.2 standard version, I am pretty sure it works even better in other games, but at least on Star Fox, the speed is the same, that is, faster than original hardware.

Still, thank you and my best regards. You guys are awesome for still developing this port on the Wii, to me is the best console for old games and 240p magnanimous retro gaming, so I thank you in the name of the old retro fans :)

Take care.

**Comment by bladeoner** [comment]
@Nashismo please test this build https://gbatemp.net/attachments/snes9x-gx-4-4-2_test-zip.163033/ I don't know if it breaks something I tried to slow down the game.

**Comment by Nashismo** [comment]
@bladeoner Awesome thank you very much. I am testing it right now. I'll be back ;)

**Comment by Nashismo** [comment]
Mmm, still faster than original hardware... Maybe there are faster versions of the game out there? Maybe my original copy is slower and not necessarily Snes9xgx being too fast?

I am going to try to download another version of the game and try again. Still, thank you for your time. I will be leaving the comments in here.

**Comment by bladeoner** [comment]
Try out no modded version, I just tested Star Fox v1.0 USA version and I get the feeling it really is slower with my adjustments.

**Comment by Nashismo** [comment]
Checking the SRC, in fact I was using the 1.0 version. Now I downloaded the 1.2 version. And no, the speed is the same.

I am simply checking the intro of the game, for times sake. I make it so the music goes exactly at the same time one version from the other, both connected to a crt, both at 240p.

Still, the 1.0 version of the game was like 1 or to second slower than the 2.0 (better but almost imperceptible). The game itself is still much faster than original.

But that would be not anyone's fault here, the main developers of Snes9x probably still having figured out how make the timing better in FX games :(

Cheers and have a very good day @bladeoner 👍

**Comment by Nashismo** [comment]
Now I have just been playing the game out of enjoyment, and it does seem to run slower! The intro timing is faster than original. Sadly I cannot figure out a way to objectively measure speed on a random play of the game.

**Comment by Nashismo** [comment]
Ok I have reach my own verdict. I went back to old 4.4.2. And yes it is faster, your latest version is slower.

But in comparison to the original cart on real SNES here is the thing: Your version even though slower than original 4.4.2 simply feels more laggy.

Is like this, original cart on SNES feels less laggy, is like the speed of the ship is slower but when shooting is fast. Your version the only thing that happens is that when shooing it becomes laggy.

I dont know how to explain it, is like the timing is slower on original hardware, the speed of the aircraft is slower and yet still fast when shooting the lasers.

Your version simply makes everything slower, the shooting and the speed of the aircraft.

I hope I explained myself somehow. The key word here is timing, and adding lag doesn't seem to help the speed of the game so to speak, sadly.

Thanks and it was fun to test this! I hope you could understan my explaining! :)

**Comment by dborth** [comment]
I'd for sure take this issue upstream to Snes9x with bearoso, this is just a simple port.

**Comment by Nashismo** [comment]
> 
> 
> I'd for sure take this issue upstream to Snes9x with bearoso, this is just a simple port.

But a very good one! Thank you Dborth!
