### ISSUE TITLE
Can't Access Controller Configuration

### ISSUE THREAD

**Issue by JackWilliams28** [dborth/snes9xgx#843]
Hello,  

I'm having trouble accessing controller configuration/button mapping. I'm very confused because it seems like the option is meant to be in the settings menu, but it is just not there... When I go to settings, I see 'Saving & Loading', 'Menu', and 'Network', and I have looked everywhere with no luck. Is something wrong, did I misunderstand, or am I crazy?

Originally I couldn't find it on Snes9x GX 4.3.2, and I just updated to 4.4.3, and it persists.

Thanks for any help you can provide.

**Comment by bladeoner** [comment]
@JackWilliams28 there are two types of settings menu's one when you still need to select a game. The other one is a little bit more 'hidden', when you start a game and then press the home button you will see another menu. Hope it helps.
