### ISSUE TITLE
WiiU pro controller as first controller turning off wiimote

### ISSUE THREAD

**Issue by ajcasanova** [dborth/snes9xgx#867]
I start emulator with wiimote, then turn on my WiiU Pro controller, but it is in player two. 

**I propuse** _a simple button to disable wiimote_ before start using WiiU Pro Controller. It would be great, because every time I play any game I have to take out the batteries, and the door of batteries has a delicated mecanism not ready for doing this every day.

This aply to Snes9xGX, VbaGX and FceuGX also.

**Comment by dborth** [comment]
This isn't as trivial as it sounds to do. Sorry, not going to tackle this
