### ISSUE TITLE
240p Menu

### ISSUE THREAD

**Issue by alexbaldwin** [dborth/snes9xgx#873]
Switching between 240p for gaming and the 480p menu causes a few second delay on most TVs. Is it possible to have the 240p video setting apply to the menu as well?

I saw that your vbagx project has this ability, but wasn't able to figure out how it's done in the code. Would be happy to contribute in developing a 240p menu.

**Comment by dborth** [comment]
You're suggesting to downscale the menu graphics to 320x240. It could be done, but it will look like crap. Because 320x240 is pretty darned low res.

**Comment by alexbaldwin** [comment]
Appreciate the prompt response. Agreed that 320x240 is _very_ low-res but I'd prefer that to ~5 seconds of downtime in-between resolution changes.

Is there a reason that vbagx does the downscaled menu in 240p video mode but it doesn't make sense for snes9xgx?

**Comment by alexbaldwin** [comment]
For reference, here's the experience comparing 240p menus in snes9xgx and vbagx.

![snes-ready](https://user-images.githubusercontent.com/305263/64716985-488ee880-d478-11e9-80d5-6ce0c786352f.gif)
> snes9xgx with a ~5 second delay while TV changes video modes.

![vba-ready](https://user-images.githubusercontent.com/305263/64716986-49277f00-d478-11e9-8ad9-f1855743dad2.gif)
> vbagx with no delay and low-res menu.

**Comment by Idiot64** [comment]
the best thing you could do is use a crt, these change modes instantly
