### ISSUE TITLE
Disable Loading Text (and Fast Forward)

### ISSUE THREAD

**Issue by TheBeverage** [dborth/snes9xgx#877]
Hi,

I've just updated to 4.4.4 and noticed ROMs now show some sort of information whenever a game is loaded. Is there any way to disable this? I don't see any setting for it, and the previous version I was using didn't seem to display it.

Also, more minor, I would like to know if there is a way to disable the fast forward function activated by pressing right on the right analog stick. I know this is an older feature but it's something that's always bugged me. 

Thanks for keeping this up to date, and thanks in advance for your help!

**Comment by bladeoner** [comment]
@TheBeverage: It is not possible to turn off the rom text information, because then we cannot use the 'Show Framerate' and the 'Show Clock' options.

The second question I don't know maybe @dborth knows that?

**Comment by TheBeverage** [comment]
Is there any way to disable the rom text when show framerate and show clock are disabled?

**Comment by TheBeverage** [comment]
I believe it could be changed with the line from this commit: https://github.com/dborth/snes9xgx/commit/f15028a5ace64ac9b76d308843d76d65d185a63e

Perhaps an option that toggles "Settings.AutoDisplayMessages" to be true or false? Unfortunately I lack the knowhow to compile my own version with that set to false.

**Comment by dborth** [comment]
Okay, I think I've disabled the rom info when show framerate and show clock are both off.

The turbo request is possible but someone would need to write the code, I'm not going to do it.

**Comment by TheBeverage** [comment]
Great, thanks a bunch!
