### ISSUE TITLE
SMB2 and SMB3 support

### ISSUE THREAD

**Issue by pmdci** [dborth/snes9xgx#882]
I just verified that snes9xgx cannot access network shares from my server unless Server Message Block v1 (SMB1) is enabled. Since SMB1 is deprecated (a major security issue due to flaws in the protocol), I was hoping that you might add support for at least SMB2 access with snes9xgx.

**Comment by dborth** [comment]
Not gonna happen. Use an SD card

**Comment by pmdci** [comment]
That is fine. I am doing that. But then you might as well remove the SMB1 support. What is the point of leaving support for a faulty, legacy protocol?

**Comment by askotx** [comment]
PR's are welcome. And you said it: legacy.
