### ISSUE TITLE
Wii U Pro Controller as Player 1

### ISSUE THREAD

**Issue by childofthegrave** [dborth/snes9xgx#883]
For some reason, no matter if there is a WiiMote as Player 1 or not, my Wii U Pro Controller is always registered as Player 2. This does not happen on VBA GX, is there any possibility of this getting fixed? I don't want a button to disable WiiMotes like the guy before me. I just want to understand why it is possible on VBA GX and not here

**Comment by dborth** [comment]
No idea. Sorry can't help you.
