### ISSUE TITLE
Gamecube build compile errors

### ISSUE THREAD

**Issue by bladeoner** [dborth/snes9xgx#889]
The following commit broke compiling the Gamecube build:
https://github.com/dborth/snes9xgx/commit/cd264c16da909099bada0c1bc9e838ec2c88620f

C:/devkitPro/examples/snes9xgx-master/source/fileop.cpp:56:33: error: '__io_gcsd2' was not declared in this scope
  const DISC_INTERFACE* port2 = &__io_gcsd2;
                                 ^~~~~~~~~~
C:/devkitPro/examples/snes9xgx-master/source/fileop.cpp:56:33: note: suggested alternative: '__io_gcsdb'
  const DISC_INTERFACE* port2 = &__io_gcsd2;
                                 ^~~~~~~~~~
                                 __io_gcsdb
make[2]: *** [/opt/devkitpro/devkitPPC/base_rules:13: fileop.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by carstene1ns** [comment]
Is your toolchain updated? You need the latest version of libfat (1.1.4) and libogc (1.8.23).
```console
$ pacman -Q libfat-ogc libogc
libfat-ogc 1.1.4-1
libogc 1.8.23-1
```

**Comment by bladeoner** [comment]
@carstene1ns that did fix it, thank you!
