### ISSUE TITLE
Texture filter on 240p mode (feature request)

### ISSUE THREAD

**Issue by Nashismo** [dborth/snes9xgx#892]
Hi dborth!

First, happy new year! I hope you remember me, I used to bother you for sound crackling issues, etc. and after a while you manage to fix all those issues!

You are simply the best. My request here is this: Could you add an option for texture filter (bilinear filter or any other) when choosing original mode (240p)?

There are some filtering options but they only work on 480i and 480p and they are not available when using 240p mode.

Could this be added dborth?

See, in games like Mortal Kombat 2, something looked off, like something was missing from playing on a real Super Nintendo and sure, that was the natural filter of not using component/rgb and it looks amazing on original SNES.

On Snes9xgx it looks too pixelated. I believe this could be possible because on Genesis Plus GX there is this awesome texture filter that you can also use at 240p mode, and let me tell you, this make the games look just as I remembered them!

It really looks beautifull at 240p with a little bit of filter :)

So that's my request, I thank you from the bottom of my heart for this emulator, my best regards,

Nashismo.

**Comment by dborth** [comment]
Sorry I wish I could help but I didn't write the texture filtering. I don't know enough to know how to make it work for 240p.

**Comment by Nashismo** [comment]
> 
> 
> Sorry I wish I could help but I didn't write the texture filtering. I don't know enough to know how to make it work for 240p.

Well, thank you anyhow. My best regards dborth.
