### ISSUE TITLE
Gamma/brightness or color palette option (feature request)

### ISSUE THREAD

**Issue by Nashismo** [dborth/snes9xgx#894]
Dear dborth:

Sorry to bother you so much. I have been tinkering here and there using the original snes and Snes9xgx and I realised of something. Sure the snes looks a bit more blurry through it's composite output, BUT there is one thing that makes it look different! This is the color gamma or brightness.

In original hardware it looks darker. That is why certain things which are not meant to be seen are seen on Snes9xgx, but just lowering the gamma it would make it much closer to original hardware.

It is not as abrupt as the problem in the NES emulator where the color palette was completely different to original hardware.

Well, this is a minor request, if you ever want to give it a go, that would be great. Maybe a gamma slider?

Happy new year and thank you for reading all this! 

I wish you the best,
Nashismo

**Comment by dborth** [comment]
There's a setting for gamma correction GX_SetDispCopyGamma

this can be set to GX_GM_1_0, GX_GM_1_7, or GX_GM_2_2. I have no idea what the difference would be. Other than that I'm not sure how you change the gamma. You would have better luck asking on gbatemp and maybe someone wants to try them out and turn it into a menu option if it changes how it looks.

**Comment by Nashismo** [comment]
Thank you for your time dborth.
