### ISSUE TITLE
Star Fox findings

### ISSUE THREAD

**Issue by Nashismo** [dborth/snes9xgx#895]
I have found that playing Star Fox on Snes9x 1.60 windows version with FX emulation at 75%, that is 25 percent slower, it works at a more correct accurate speed, very similar if not almost exactly as original hardware.

Could you implement a downclock feature for Snes9xGX? Bearoso said the feature was there for developers to use it if they wanted.

Better yet would be a simple hack for this game, I think I bothered you about this subject before, but maybe we could try one last time?

Thank you Dborth, thank you for everything.

I guess it would be easier to port bsnes/hygan (performance mode) to the Wii than try to fix Super FX on Snes9x. Do you think a bsnes in performance mode could run on the Wii? Or this is just imposible?

**Comment by Nashismo** [comment]
Askotx, I was waiting for dborth to respond to this, he knows me and this is my way of talking to him. No need to actually "change" anything on the emulator.

**Comment by askotx** [comment]
Mate, do you know that wii has only ~700Mhz of power and that bsnes requires 3Ghz (3,000Mhz) at least to run? You don't need to create an issue for that kind of questions, sorry, still closed.

**Comment by Nashismo** [comment]
> 
> 
> Mate, do you know that wii has only ~700Mhz of power and that bsnes requires 3Ghz (3,000Mhz) at least to run? You don't need to create an issue for that kind of questions, sorry, still closed.

That was only a silly question I added at the end, the main feature I am requesting is Super FX downcloking. If dborth is busy, that's OK, I will open a feature request at a later time, as this is dborth github page, not yours.
