### ISSUE TITLE
Classic Controller Pro Analog Don't Work

### ISSUE THREAD

**Issue by Repliroid** [dborth/snes9xgx#904]
The Left Analog Don't Work on emulator.
My Controller is a Classic Controller PRO Black Parallel.
All other buttons work perfectly! only the Analog don't work.
The same happens on Fceultra GX and Visual Boy Advance GX.
On the Genesis Plus GX the Analog Works Perfectly.

**Comment by dborth** [comment]
[controller-test.zip](https://github.com/dborth/snes9xgx/files/4239585/controller-test.zip)

Run this and report the results when the analog stick is stationary, pushed to the left, and pushed to the right.

**Comment by Repliroid** [comment]
I run the test but I don't understand anything...

ccl pos x =32
ccl min x = 63
ccl max x = 63

ccl pos y = 32
ccl min y = 63
ccl max y = 63

ccl mag = inf
ccl ang = -135.000000

ccr pos x = 16
ccr min x = 31
ccr max x = 31

ccr pos y = 16
ccr min y = 31
ccr max y = 31

ccr mag = inf
ccr ang = -135.000000

The Classic controller pro parallel it is very difficult to make it work on homebrews.
the Wiimote stops working when the controller is plugged in.
and I have a lot of Crash Exeptions.
but, in the Wii Menu, the Controller Works Perfectly.

**Comment by dborth** [comment]
[snes9xgx-wii.zip](https://github.com/dborth/snes9xgx/files/4270576/snes9xgx-wii.zip)
Let me know if this works.

**Comment by bladeoner** [comment]
@dborth with commit https://github.com/dborth/snes9xgx/commit/05b4abce9812760e57bc86de33b8896b70216617 I'm getting a DSI dump crash when I plug in my Snes Classic Controller.

**Comment by dborth** [comment]
@bladeoner does the above dol work for you?
If yes that's important for me to know.
If no, can you run this controller test? it's different from the one above - it also reports the center.
[controller-test2.zip](https://github.com/dborth/snes9xgx/files/4272086/controller-test2.zip)

**Comment by bladeoner** [comment]
> @bladeoner does the above dol work for you?
> If yes that's important for me to know.
> If no, can you run this controller test? it's different from the one above - it also reports the center.
> [controller-test2.zip](https://github.com/dborth/snes9xgx/files/4272086/controller-test2.zip)

Is the one from two days a go the compiled version of the latest commit? If so that's working, I've tested it with Snes9x GX but also with the NES and GBA emulators. 

I thought the latest commit caused an issue but it was caused by a portlib that was updated/overwritten in my build environment. After reverting that it was fine.

**Comment by Repliroid** [comment]
Yeah!!!
@dborth This new version works perfectly for me!
You’re the best! Thanks a million for the help!
