### ISSUE TITLE
Gamecube version not loading anything

### ISSUE THREAD

**Issue by hfc2x** [dborth/snes9xgx#906]
**Feature requests will be closed immediately!**

**Describe the bug**
When booting the Gamecube DOL file, the screen shows the backdrop for Snes9xGX, but nothing else besides that. Loaded through the latest version of Swiss (r785 at the time of writing) and through SD Gecko in Memory Card slot B. Probably doing something wrong, but there are no instructions for the Gamecube version.

**To Reproduce**
Put snes9xgx.dol in the root of the SD card, and created folder "snes9xgx" also at the root. Inside said folder, created the folders "cheats", "roms" and "saves", and put some SNES ROM files inside the "roms" folder.  Loaded Swiss r785 through DVD image, and selected "snes9xgx.dol" to boot. The resulting screen is permanently empty and no action can be performed whatsoever. SD card is not write-protected.

**Expected behavior**
At least a file with the name "settings.xml" should be created at the same location as the DOL file, according to the instructions, but no such file is created. Main screen of Snes9xGX should show a file browser, but this doesn't happen either.

**Screenshots**
![Snes9xGX](https://user-images.githubusercontent.com/8249996/75123249-998c4500-5684-11ea-9555-a2956cdb12c7.png)

**Comment by dborth** [comment]
I can't help you much with this, I use a Wii. I'd suggest to ask on gbatemp or gcforever

**Comment by dborth** [comment]
@emukidid have you tried this port2 stuff? any idea what's going on here? Looks like it locks up when you don't have a sd port 2 device as per this issue and https://github.com/dborth/fceugx/issues/404

**Comment by bladeoner** [comment]
@dborth I want to suggest to remove the serial port 2 commits for now, in all three emulators until further investigation.

I also don't have a Gamecube so I can't help with that.

**Comment by emukidid** [comment]
@dborth, you need the latest libOGC from the git source

**Comment by dborth** [comment]
Still didn't work apparently. I've removed the mounting call on startup and apparently that works. probably some lwp deadlock.
