### ISSUE TITLE
Classic Controller Fast Forward Button Map Issue

### ISSUE THREAD

**Issue by wildmattata** [dborth/snes9xgx#908]
Using Chrono Trigger as an example, emulator version 4.4.6:

When Im on the overworld map, if I press right on the right analog stick to fast forward, my character walks up. If I do it in battle, the menu cursor scrolls upwards on its own. It seems to be registering me holding up on the d-pad while holding right on the right analog stick to fast forward. This makes using fast forward a pain and borderline unusable. This does happen with every game but I used CT as the example since it's what I'm playing.

**Comment by dborth** [comment]
I can't reproduce this. 
[controller-test.zip](https://github.com/dborth/snes9xgx/files/4290427/controller-test.zip)

Perhaps run this controller test with no analog sticks or buttons pressed, and then again with the right analog stick pressed to the right and report the two different outputs here. that will test us what values the stick is reporting

**Comment by wildmattata** [comment]
![IMG_6080](https://user-images.githubusercontent.com/45305666/75942515-8d606e80-5e60-11ea-99aa-d366778d064a.JPG)
![IMG_6081](https://user-images.githubusercontent.com/45305666/75942519-8f2a3200-5e60-11ea-908a-16af161d57d9.JPG)

First picture is with nothing pressed, second is with the right stick pressed all the way to the right.

**Comment by dborth** [comment]
yeah it's as I feared, when you press the right stick right it is also changing the left stick values. 
ccl = left stick, ccr = right stick

nothing can be done, aside from changing the mapping from right stick right to something else, or making it customizable.
