### ISSUE TITLE
Graphics bug/Boxart stops loading (GC)

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/snes9xgx#910]
At first all seems normal. But
loading a ROM then exiting then loading it again will produce multiple gfx bugs. 

Untested on the Wii port. Doesn't happen on fceugx. Untested on the vbagx ports.

https://imgur.com/a/7BmdKtB

**Comment by dborth** [comment]
[snes9xgx-gc.zip](https://github.com/dborth/snes9xgx/files/4303953/snes9xgx-gc.zip)

Does this version work better?

**Comment by 60fpshacksrock** [comment]
Will test and report back. Hopefully tomorrow.

**Comment by 60fpshacksrock** [comment]
I mean't Sunday, apologies.

As for you question yes I believe it's fixed as I haven't seen any more gfx bugs.
