### ISSUE TITLE
Request: Option to overclock main CPU

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/snes9xgx#912]
I would like to request this feature for the gx port. The retroarch version(s) have so I was wondering if you would be willing to add it. 

Maybe 1.5x/2x speed.

**Comment by 60fpshacksrock** [comment]
No reply?

**Comment by askotx** [comment]
No feature requests, PR's are welcome, it's on New Issue template.

**Comment by 60fpshacksrock** [comment]
I wondered if I should have used the PR section. 

Thanks for letting me know

**Comment by 60fpshacksrock** [comment]
I can't create a pull request. Can someone tell me what I'm doing wrong?

I am not a developer and don't have that status. Is this why I can't create a PR?
