### ISSUE TITLE
Running on USB HDD, scrolling through the ROMs with covers list crashes after 5-10 seconds

### ISSUE THREAD

**Issue by binarymale** [dborth/snes9xgx#923]
In version 4.4.7 when running on USB HDD, scrolling through the ROMs with covers list crashes after 5-10 seconds. If running on SD card its fine.
VBAGX 2.4.0 is fine without crashing on both USB HDD and SD card, also shows covers for ROMs in the list.

**Comment by dborth** [comment]
I can't reproduce this. It's working fine for me. Perhaps you have a bad image in your snes library?
or perhaps you need to run a chkdsk on your drive?
