### ISSUE TITLE
snes9xgx Not Working With Swiss v0.5r845 With Xeno via Gamecube SD2SP2 and Gecko: Stuck on "Loading DVD"

### ISSUE THREAD

**Issue by ThemUsersIhate** [dborth/snes9xgx#927]
**Describe the bug**
Everytime I try to booting Snesxgx It will get stuck/freezes at the "Loading DVD" screen.
Hear is the reddit post I made along with the video:
https://www.reddit.com/r/Gamecube/comments/hef1t9/problem_cant_get_snes9_gx_working_on_my_sd2sp2/

**To Reproduce**
I have tried using a Gecko in memory slot B, this gives the same result as the SD2SP2. I have also tried downloading the wii version and copy the file path over: snesxgx/roms saves cheats. This didn't work either so I tried taking the wii meta.xml file renaming it to settings.xml and putting it on the root of my sd card where the snes9xgx.dol file is located. Still nothing.

**Expected behavior**
I would expected it to load into the menu where I can select my SNES Roms.

Hardware information
Modded DOL-001(EUR) GameCube with a XENO GC 2.0
Burnt Swiss Swiss v0.5r845 boot disc
and SD2SP2. I have a Gecko memory card.

**Screenshots**

![Screenshot from 2020-06-24 08-48-11](https://user-images.githubusercontent.com/67349299/85483495-7c965d00-b5f7-11ea-9805-4e78d1c84783.png)

**Comment by dborth** [comment]
Since I don't own one of these it's kinda hard for me to help you. I'd suggest to go ask on https://www.gc-forever.com/
