### ISSUE TITLE
Compile fails after updating to latest devkitPro tools

### ISSUE THREAD

**Issue by bladeoner** [dborth/snes9xgx#928]
**Feature requests will be closed immediately!**

**Describe the bug**
Compiling will fail after updating to the latest devkitPro toolkit

**To Reproduce**
Install devkitPro and update all.

**Expected behavior**
After installing the latest devkitPro and start a build it will fail.

**Screenshots**

[Logfile.txt](https://github.com/dborth/snes9xgx/files/4838287/Logfile.txt)

**Comment by bladeoner** [comment]
@dborth The warnings seems it can be solved by applying the following structure:

This warning tells us that buffers passed to sprintf should not overlap, so I changed every occurence of
sprintf(str, "%sABC", str)
to
sprintf(str + strlen(str), "ABC")

Source: https://github.com/lwfinger/rtl8188eu/pull/328

But I still cannot figure out why it fails.

**Comment by carstene1ns** [comment]
Most of the time `sprintf` is overkill anyway when adding just an extension. `strcat` can do the same.
