### ISSUE TITLE
Not reading correctly a SD card on Game Cube

### ISSUE THREAD

**Issue by RodZaramella** [dborth/snes9xgx#932]
**The Bug**
Trying to load the Game cube DOL version, an "Error opening directory" message shows up when booted on a Gamecube SD Gecko, after this shows this strange characteres (photos) and can't navigate to the correct folders. Same problem in the 4.4.7 release. The only version I tested before, was the 4.1.1. That one works very well on a real NGC.
Sorry for the quality, is a photo from my CRT television.

**To Reproduce**
Booted from a modded Gamecube with Qoob Pro, than SWISS, than the "snes9xgx-gc.dol"

**Screenshots**
![IMG_20200630_015903](https://user-images.githubusercontent.com/67621962/86086220-96acc100-ba77-11ea-981b-d1b578a95daa.jpg)
![IMG_20200630_020436](https://user-images.githubusercontent.com/67621962/86086229-9dd3cf00-ba77-11ea-8481-0ca3ac71866b.jpg)

**Comment by carstene1ns** [comment]
The corrupted texts you are seeing are parts of the xml configuration file. Could be some kind of memory corruption or maybe a broken file system. Have you checked other homebrew besides swiss with your SD card? (reason is swiss uses fatfs, most homebrew uses libfat)

**Comment by dborth** [comment]
I agree, it seems like it's an issue with the file system on that SD card. I'd suggest to run a chkdsk or try another one. Or both.

**Comment by RodZaramella** [comment]
Well, is just this one having this issue... I've changed the SD, formatted differently... Same thing. Is there a "correct way" to format? All other emulators works fine on my GameCube.

**Comment by dborth** [comment]
That's strange. Does FCE Ultra GX work fine?

**Comment by RodZaramella** [comment]
> That's strange. Does FCE Ultra GX work fine?

Yes. FCE Ultra GX working fine, and all the bunch of emulator. I'm trying older versions of snes9xgx... 4.1.7 works the best in real Gamecube (similar to 4.1.1), anything between 4.1.2 ~ 4.1.7 had problems. 4.4.5~4.4.7 had the same problem of the 4.4.8 or show only the backgroud.

**Comment by dborth** [comment]
Have you tried deleting the settings.xml?

**Comment by RodZaramella** [comment]
Yes, and I trying again,
Only correcting one thing (don't know if this make any difference), but the SD adaptor I'm using is the Wii SD (or something like that :D) and not SD gecko. Photo:
![adaptador-leitor-de-carto-sd-wii-e-gamecube-leia-o-anuncio-D_NQ_NP_600913-MLB40375998583_012020-F](https://user-images.githubusercontent.com/67621962/86203005-303ca700-bb3a-11ea-82fc-ae7bd375b01c.jpg)

**Comment by RodZaramella** [comment]
UPDATE: Trying something new... Not creating the snes9xgx folder, the emulator' screen now shows the other folders and I can move the cursor by then. But when I tried to enter any of those, the message "Error opening directory" apears.

**Comment by carstene1ns** [comment]
"WiiSD" is just a brand name of SD Geckos. So it does not make a difference.

**Comment by RodZaramella** [comment]
But thats ok. For now I'll stick with version 4.1.7 on my GC. If you want me to test files on gamecube, I'll be happy to do so.

**Comment by Retropanda88** [comment]
Pregunta de novato por qué el audio en gamecube no suena bien cuando haces streaming desde las sd?  Es decir el audio suena con corte
