### ISSUE TITLE
UI GFX issues still persisting

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/snes9xgx#938]
I hate to open a new issue on this but I noticed a similar problem where the background, not the game list but the graphics behind the game list overlay and also behind the settings overlay goes black after playing about 5 or maybe more games.

This is happening on GC, untested on Wii.
If it helps to know, although it may be unrelated is that I have a subdirectory in the main roms folder on SDGecko Slot B named hacks which mainly consists of Super Mario World hacks.

**Comment by dborth** [comment]
Sounds like some sort of memory corruption issue. I can't reproduce this so I need some help. Can you help narrow it down?

- are you using cover images at all?
- are your roms zip or 7z?
- if you do something much simpler like have only 10 games in the directory, and they're all zipped, and then load them 1 by 1, can you still reproduce?

[snes9xgx-gc.zip](https://github.com/dborth/snes9xgx/files/4973697/snes9xgx-gc.zip)

Does the attached version have the same issue?

**Comment by 60fpshacksrock** [comment]
Yes I do use covers, but the for the ROM hacks I don't, even though some ROM hacks do have custom art.

Only zip format because some older emulators on my PC don't support 7zip.

I will try your suggestion and the new build and report back later. Thanks.

**Comment by 60fpshacksrock** [comment]
Tried two games, same problem. And when it occurs the boxarts also stop loading 

You could build a bootable homebrew iso for Dolphin and point all the paths to their DVD directory equivalents you might could use it for testing.

**Comment by 60fpshacksrock** [comment]
Set display to not show boxart and same issue persists.

**Comment by dborth** [comment]
What's the file size of your largest cover image?

**Comment by 60fpshacksrock** [comment]
Will check and let you know.

Sorry for the late reply. I didn't know you replied again.

**Comment by 60fpshacksrock** [comment]
The largest file is, in bytes 206,500 or 201/202 kilobytes and its dimensions are 316x224.
