### ISSUE TITLE
Original video mode not original

### ISSUE THREAD

**Issue by Idiot64** [dborth/snes9xgx#944]
**Feature requests will be closed immediately!**

**Describe the bug**
Its 480i not 240p the original snes had 240p

**To Reproduce**
set video mode to original

**Expected behavior**
as said the original video mode was 240p so i expect that
its a fuzzy image and annoys

**Screenshots**

**Comment by dborth** [comment]
You're correct, the "original" mode in this emulator is 224/239 overlayed onto 480 / 576. I have no intention of adding the actual original modes.
