### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Idiot64** [dborth/snes9xgx#945]
**Feature requests will be closed immediately!**

**Describe the bug**
I can't compile the wii version i am getting an error

**To Reproduce**
I downloaded everything and put it in the correct folders

**Expected behavior**
Compile.

**Screenshots**

here's a screen shot:

https://prnt.sc/u4k4qh

(sorry i haven't compiled anything before)

**Comment by askotx** [comment]
If you have "everything and put it in the correct folders" then it should compile fine, but this is not an issue, you're requesting help for compiling, sorry this is not a forum for asking for that, maybe in gbatemp or check wiibrew ... closing.
