### ISSUE TITLE
Latest version does not load .zip, .smc, or .sfc on GameCube

### ISSUE THREAD

**Issue by coolaj86** [dborth/snes9xgx#950]
I'm using a GameCube DOL-001 (because it supports HDMI, and my SNES games deserve the best) and no .zip, .smc, or .sfc games will load.

# Describe the bug

v4.1.8 on the GameCube always opens to this error

> Error opening directory!

After hitting Retry and opening a game

> Unsupported Game Format (I think, I don't recall exactly)

# Workaround

I tried v4.1.7 because I found a thread referencing that as a working version for another issue, and it works.

After getting things working with the old version, it now works with the new version.

# To Reproduce

1. Get a FAT32 formatted 1GB SD Card
1. Download `Snes9xGX-4.4.8-GameCube.zip`
2. Copy `snes9xgx-gc.dol` as `snes9xgx-gc-4.4.8.dol` to the SD card root
3. Create a `snes9xgx` folder in the root of the card
4. Copy a few .zip, .smc, and .sfc game backups into the SD card root
5. Copy a few .zip, .smc, and .sfc game backups into `snex9xgx`
6. Put the card in a SD Gecko in Slot B
7. Boot with Wind Waker Hack from Slot A into Swiss v0.4r714
8. Open `snes9xgx-gc-4.4.8.dol`
9. Try opening a game from the SD card root

For reference: I'm using the built-in SD card slot of a 2012 MacBook Pro running macOS High Sierra.

# Expected behavior

Game should play, right?

**Comment by coolaj86** [comment]
Interestingly, after playing the games with v4.1.7 and switching back to v4.4.8, it now works also. No more directory error, nor file load error.

Something strange is going on...

**Comment by dborth** [comment]
Honestly to get to the bottom of these GameCube issues will take someone who has all the hardware already and with an interest in solving it. The issues here are with the libraries this app uses - libogc, libfat, devkitPPC. It'll require some lower-level digging that I just won't do.

**Comment by Papy-G** [comment]
It's ok if the game comes with the folder and conf. file inside it, otherwise, it doesn't seem to be able to create it.
Exact same problem with fceugx.
Hope this helped!
