### ISSUE TITLE
USB disk not detected

### ISSUE THREAD

**Issue by asheenlevrai** [dborth/snes9xgx#951]
Hi :)

On my modded Wii, my USB disk **is not** detected by SNES9X gx (while the USB disk **is** detected by by other apps) when:
 - USB disk is GUID
**OR**
 - USB disk is formated as exFAT (didn't try with NTFS)

my USB disk **is** detected by SNES9X when
 - USB disk is MBR **AND** is formatted as FAT32 (didn't try with NTFS).

How come SNES9X cannot see USB disks when other apps can?

Thank you very much in advance for your help.
Best,
-a-

**Comment by dborth** [comment]
Because that support isn't in this app, and never will be.

**Comment by asheenlevrai** [comment]
OK. Thanks.

Disk support is provided by who/what app then?
I'm sorry I am not familiar with all this yet.

Best,
-a-
