### ISSUE TITLE
can't save game data on gcn using sd2sp2

### ISSUE THREAD

**Issue by aleczdr** [dborth/snes9xgx#952]
on gcn, snes9xgx can load games from sd2sp2, but it can't load or save save data to it. also, there is no way to set sd2sp2 as the default device, you have to use sd gecko a or b and go to the top of the directory.

**Comment by bladeoner** [comment]
@aleczdr could you try the attached file? 
[Snes9xGX-GameCube.zip](https://github.com/dborth/snes9xgx/files/5898231/Snes9xGX-GameCube.zip)

**Comment by dborth** [comment]
[snes9xgx-gc.zip](https://github.com/dborth/snes9xgx/files/5898463/snes9xgx-gc.zip)

Can you try this DOL? 

If possible can you confirm the following?

- sd2sp2 plugged in, loads right after launch (your scenario)
- sd2sp2 unplugged, then load the emulator, then if you plug in sd2sp2 after it works
- sd gecko in port A and B (if you own one)

**Comment by bladeoner** [comment]
@aleczdr did you update Swiss to the latest version?

I just tested with Swiss from March 2020, with it Snes9x GX 4.4.9 and the version I just uploaded are working.

@dborth The changes I in with the PR are to correct the path to SD2SP2. The issue seems to be related to the Swiss version used.

**Comment by aleczdr** [comment]
@bladeoner I've just tried the file you sent me and can confirm that it is indeed working. I have been using swiss from september 2020. Before, sd2sp2 was only an option for the load device, not the save device, and the file fixed it.
