### ISSUE TITLE
Only 2 players detected

### ISSUE THREAD

**Issue by asheenlevrai** [dborth/snes9xgx#954]
**Describe the bug**

Players 3 and 4 are not detected in games that support more than 2 players (at least SuperBomberman3)

**To Reproduce**
 Connect a SNES classic controller to a wiimote. Repeat this 4 times.

**Expected behavior**
All gamepades connected to a wiimote linked to the wii are expected to be detected and allow gameplay

Hi :)

In order to play SuperBomberman3 with three other friends just like we did when we were kids, I connected a SNES classic controller to each of the 4 wiimotes that I have linked to my Wii and launched SB3 in SNES9X GX. However, it seems like only
2 players are detected while the input from the 3rd and 4th gamepads are not detected at all. I'm obviously very sorry about that and I was wondering if anything could be done to fix this bug.

Thank you very much in advance for your help.
Happy gaming,
-a-

**Comment by dborth** [comment]
Turn on the multi-tap in the settings.

**Comment by asheenlevrai** [comment]
Thank you so much :)
Pardon my ignorance and thank you again for your time.
Best,
-a-
