### ISSUE TITLE
Some controllers are not recognized

### ISSUE THREAD

**Issue by mickro** [dborth/snes9xgx#956]
**Describe the bug**
Some controller controller are not recognized.

| controller | work in menus | work in game |
| ---- |  ---- |  ---- | 
| original wiimote | yes | yes |
| original wiimote + original numchuck | yes | no |
| orginal wiimote + generic gamepad  | no | no |
| generic wiimote + generic numchuck | yes | yes |
| generic wiimote + generic gamepad | yes | yes |
| generic gamecube controller | yes | no |

Those results are stable.

**To Reproduce**
Plug the wiimote before starting the emulator or changing while the emulator is running. It is not recognized in snes9xgx according to above matrix.

**Expected behavior**
It should be able to play with any controller configuration.

**Comment by mickro** [comment]
I updated my issue with a test table and different controller configuration.

**Comment by dborth** [comment]
The controller support has nothing to do with this project, the libraries don't support all controllers. Nothing I can do about that.

**Comment by mickro** [comment]
[In features](https://github.com/dborth/snes9xgx#features) of this project we have:
 
> Wiimote, Nunchuk, Wii Classic, Wii Pro, Wii Super NES Classic, Wii U Pro, and Gamecube controller support

on some release messages with even have some fixes related to 3rd party controller:

> [4.4.7 - March 4, 2020]
> Fixed 3rd party controllers (again)

How _controller support has nothing to do with this project_?

The issue I describe is about **official wiimote + numchuck** first. Then some 3rd party controllers.

Where should I look to have controllers work if not here?

**Comment by dborth** [comment]
That's changes I made upstream that got committed: https://github.com/devkitPro/libogc/commit/dc2451fd85f2943738bb106b08e648b645542336
