### ISSUE TITLE
L+R+Start does not go back to emulator

### ISSUE THREAD

**Issue by setiawanj** [dborth/snes9xgx#964]
**Description**
Pressing the L trigger + R trigger + Start button simultaneously, while in a game, does not do anything. 

Individually, the keys work as expected in games. I am using version 4.5.1 on an original Wii. The controller is the SNES mini controller, connected to the bottom of a Wii remote.

**Reproduction**
1. Start Snes9x GX (whether from Homebrew Channel, forwarder, or some other way).
2. Browse for a valid ROM file and open it.
3. During any part of gameplay, press the button combination L + R + Start.

**Expected behavior**
As per release notes of 4.4.4, I would expect that pressing the button combination would "go back to emulator". This is a little ambiguous, so my interpretation is that during emulation of a game, pressing L + R + Start on a connected controller would bring up the game menu (i.e. the menu that is opened when pressing the Home button on the Wii remote).

**Comment by dborth** [comment]
that's because that key combo was only added for gamecube controllers. try this out and let me know if it works.
[snes9xgx-test.zip](https://github.com/dborth/snes9xgx/files/5973220/snes9xgx-test.zip)

**Comment by setiawanj** [comment]
Just tried out the test `boot.dol` file you provided using the SNES mini controller and it seems to fix the problem. I don't have any other controllers to test with unfortunately, but speaking for myself, it appears to be fixed.

Thanks!
