### ISSUE TITLE
There has been only 2 bugs with the emulator from my experience 

### ISSUE THREAD

**Issue by RazorVermillion** [dborth/snes9xgx#966]
1. Bug is with the screenshots, covers, artworks not working.
- Yes they're PNG files and yes I've used the emulator's screenshot feature and made sure the emulator screenshot path is:
snes9xgx/screenshots and for some reason the newer builds of the emulator has been not showing the screenshots I've made.
I've also made sure there's lower case and upper cased and still no luck of it working, i've never had this problem with the older builds of this emulator.

2. Bug with the cheats not working with double codes like here and codes that have = and codes with spaces too.

![2](https://user-images.githubusercontent.com/79543686/108908013-d751df80-75f0-11eb-8d90-9c421671be67.png)

Here's screenshot of what the bug looks like
![Screenshot 2021-02-23 15-57-23](https://user-images.githubusercontent.com/79543686/108907229-d7051480-75ef-11eb-8ad8-841e10426761.png)

I really enjoy this emulator and looking forward in the future for more updates.

**Comment by RazorVermillion** [comment]
just to keep in mind, this is for Nintendo Wii real hardware.

**Comment by dborth** [comment]
Glad you're enjoying the emulator.

There was a recent change for image dimensions, they're now limited to 640x480 I think. There's also a size limit. Definitely this feature is still working, I bet you're hitting this. Only other thing to check is the format, there's a few different png formats and I don't think they all are supported.

Regarding the double quotes, I'll accept a PR to fix that, but don't intend code support for that myself.

**Comment by RazorVermillion** [comment]
I also tried to resized my png file to 640x480 using paint.net and still no luck. Tried to lower the size limit to 122kb by lowering the quality of the file and also sadly didn't show up either on the emulator game selection screen.

I've also tried a different game that didn't have any screenshots and tried to make a screenshot using the newest build of the emulator and it doesn't create a screenshot at all for me, Made sure the folder and the path of the screenshots set too but it just doesn't create screenshots on the real hardware of the Wii.

**Comment by InfiniteBlueGX** [comment]
@RazorVermillion a fix for the cheats issue you were seeing was merged today: https://github.com/dborth/snes9xgx/pull/1038. The fix will presumably be in the next release, where you can now use the new format of .cht files in Snes9xGX.

As for the screenshots not showing, you might have inadvertently pressed the toggle button that switches between them and the artwork/covers. Try highlighting a game in the menu that you know has a screenshot taken, then press the Plus button (or GC controller Z button) several times in a row. Let me know if that works for you.
