### ISSUE TITLE
Bass Masters Classic - Pro Edition no longer runs.

### ISSUE THREAD

**Issue by VulcanBrady** [dborth/snes9xgx#972]
**Feature requests will be closed immediately!**

**Describe the bug**
Any attempt to load any version/dump of this game now loads a black screen, and the game never starts. Game ran fine in older versions.

**To Reproduce**
Load the game ROM for "Bass Masters Classic - Pro Edition (NTSC/USA).

**Expected behavior**
Game will not load, black screen will be displayed. Can still return to menu and choose another game (so it's not freezing I guess)

**Screenshots**
N/A

**Comment by dborth** [comment]
What version did the game last work in?

**Comment by VulcanBrady** [comment]
4.1.5 is the last version the ROM loaded/ran on. I just checked every version back to that one. So it's been broken since 4.1.6 if that helps.

**Comment by dborth** [comment]
Yeah that helps a lot. Looks like this has been broken in snes9x itself for a long time, I'd try it on snes9x itself and ask there https://github.com/snes9xgit/snes9x

**Comment by VulcanBrady** [comment]
> Yeah that helps a lot. Looks like this has been broken in snes9x itself for a long time, I'd try it on snes9x itself and ask there https://github.com/snes9xgit/snes9x

Thanks, I tried. Loads fine on all versions of the windows and linux up to current 1.60. Just no longer works on the Wii/WiiU
